CREATE TABLE parents(
	id BIGINT(5) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    initials VARCHAR(5) NOT NULL

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE state (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    initials VARCHAR(2) NOT NULL,
    id_parents BIGINT(20) NOT NULL,
    FOREIGN KEY (id_parents) REFERENCES parents(id)
    
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE city (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    id_state BIGINT(20) NOT NULL,
    FOREIGN KEY (id_state) REFERENCES state(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;