INSERT INTO city(id,name,id_state) VALUES(3161, 'Manga', 11);
INSERT INTO city(id,name,id_state) VALUES(3162, 'Manhuacu', 11);
INSERT INTO city(id,name,id_state) VALUES(3163, 'Manhumirim', 11);
INSERT INTO city(id,name,id_state) VALUES(3164, 'Mantena', 11);
INSERT INTO city(id,name,id_state) VALUES(3165, 'Mantiqueira', 11);
INSERT INTO city(id,name,id_state) VALUES(3166, 'Mar de Espanha', 11);
INSERT INTO city(id,name,id_state) VALUES(3167, 'Marambainha', 11);
INSERT INTO city(id,name,id_state) VALUES(3168, 'Maravilhas', 11);
INSERT INTO city(id,name,id_state) VALUES(3169, 'Maria da Fe', 11);
INSERT INTO city(id,name,id_state) VALUES(3170, 'Mariana', 11);
INSERT INTO city(id,name,id_state) VALUES(3171, 'Marilac', 11);
INSERT INTO city(id,name,id_state) VALUES(3172, 'Marilandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3173, 'Mario Campos', 11);
INSERT INTO city(id,name,id_state) VALUES(3174, 'Maripa de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3175, 'Marlieria', 11);
INSERT INTO city(id,name,id_state) VALUES(3176, 'Marmelopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3177, 'Martinesia', 11);
INSERT INTO city(id,name,id_state) VALUES(3178, 'Martinho Campos', 11);
INSERT INTO city(id,name,id_state) VALUES(3179, 'Martins Guimaraes', 11);
INSERT INTO city(id,name,id_state) VALUES(3180, 'Martins Soares', 11);
INSERT INTO city(id,name,id_state) VALUES(3181, 'Mata Verde', 11);
INSERT INTO city(id,name,id_state) VALUES(3182, 'Materlandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3183, 'Mateus Leme', 11);
INSERT INTO city(id,name,id_state) VALUES(3184, 'Mathias Lobato', 11);
INSERT INTO city(id,name,id_state) VALUES(3185, 'Matias Barbosa', 11);
INSERT INTO city(id,name,id_state) VALUES(3186, 'Matias Cardoso', 11);
INSERT INTO city(id,name,id_state) VALUES(3187, 'Matipo', 11);
INSERT INTO city(id,name,id_state) VALUES(3188, 'Mato Verde', 11);
INSERT INTO city(id,name,id_state) VALUES(3189, 'Matozinhos', 11);
INSERT INTO city(id,name,id_state) VALUES(3190, 'Matutina', 11);
INSERT INTO city(id,name,id_state) VALUES(3191, 'Medeiros', 11);
INSERT INTO city(id,name,id_state) VALUES(3192, 'Medina', 11);
INSERT INTO city(id,name,id_state) VALUES(3193, 'Melo Viana', 11);
INSERT INTO city(id,name,id_state) VALUES(3194, 'Mendanha', 11);
INSERT INTO city(id,name,id_state) VALUES(3195, 'Mendes Pimentel', 11);
INSERT INTO city(id,name,id_state) VALUES(3196, 'Merces', 11);
INSERT INTO city(id,name,id_state) VALUES(3197, 'Merces de Agua Limpa', 11);
INSERT INTO city(id,name,id_state) VALUES(3198, 'Mesquita', 11);
INSERT INTO city(id,name,id_state) VALUES(3199, 'Mestre Caetano', 11);
INSERT INTO city(id,name,id_state) VALUES(3200, 'Miguel Burnier', 11);
INSERT INTO city(id,name,id_state) VALUES(3201, 'Milagre', 11);
INSERT INTO city(id,name,id_state) VALUES(3202, 'Milho Verde', 11);
INSERT INTO city(id,name,id_state) VALUES(3203, 'Minas Novas', 11);
INSERT INTO city(id,name,id_state) VALUES(3204, 'Minduri', 11);
INSERT INTO city(id,name,id_state) VALUES(3205, 'Mirabela', 11);
INSERT INTO city(id,name,id_state) VALUES(3206, 'Miradouro', 11);
INSERT INTO city(id,name,id_state) VALUES(3207, 'Miragaia', 11);
INSERT INTO city(id,name,id_state) VALUES(3208, 'Mirai', 11);
INSERT INTO city(id,name,id_state) VALUES(3209, 'Miralta', 11);
INSERT INTO city(id,name,id_state) VALUES(3210, 'Mirantao', 11);
INSERT INTO city(id,name,id_state) VALUES(3211, 'Miraporanga', 11);
INSERT INTO city(id,name,id_state) VALUES(3212, 'Miravania', 11);
INSERT INTO city(id,name,id_state) VALUES(3213, 'Missionario', 11);
INSERT INTO city(id,name,id_state) VALUES(3214, 'Missoes', 11);
INSERT INTO city(id,name,id_state) VALUES(3215, 'Mocambeiro', 11);
INSERT INTO city(id,name,id_state) VALUES(3216, 'Mocambinho', 11);
INSERT INTO city(id,name,id_state) VALUES(3217, 'Moeda', 11);
INSERT INTO city(id,name,id_state) VALUES(3218, 'Moema', 11);
INSERT INTO city(id,name,id_state) VALUES(3219, 'Monjolinho de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3220, 'Monjolos', 11);
INSERT INTO city(id,name,id_state) VALUES(3221, 'Monsenhor Horta', 11);
INSERT INTO city(id,name,id_state) VALUES(3222, 'Monsenhor Isidro', 11);
INSERT INTO city(id,name,id_state) VALUES(3223, 'Monsenhor Joao Alexandre', 11);
INSERT INTO city(id,name,id_state) VALUES(3224, 'Monsenhor Paulo', 11);
INSERT INTO city(id,name,id_state) VALUES(3225, 'Montalvania', 11);
INSERT INTO city(id,name,id_state) VALUES(3226, 'Monte Alegre de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3227, 'Monte Azul', 11);
INSERT INTO city(id,name,id_state) VALUES(3228, 'Monte Belo', 11);
INSERT INTO city(id,name,id_state) VALUES(3229, 'Monte Carmelo', 11);
INSERT INTO city(id,name,id_state) VALUES(3230, 'Monte Celeste', 11);
INSERT INTO city(id,name,id_state) VALUES(3231, 'Monte Rei', 11);
INSERT INTO city(id,name,id_state) VALUES(3232, 'Monte Santo de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3233, 'Monte Siao', 11);
INSERT INTO city(id,name,id_state) VALUES(3234, 'Monte Verde', 11);
INSERT INTO city(id,name,id_state) VALUES(3235, 'Montes Claros', 11);
INSERT INTO city(id,name,id_state) VALUES(3236, 'Montezuma', 11);
INSERT INTO city(id,name,id_state) VALUES(3237, 'Morada Nova de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3238, 'Morro', 11);
INSERT INTO city(id,name,id_state) VALUES(3239, 'Morro da Garca', 11);
INSERT INTO city(id,name,id_state) VALUES(3240, 'Morro do Ferro', 11);
INSERT INTO city(id,name,id_state) VALUES(3241, 'Morro do Pilar', 11);
INSERT INTO city(id,name,id_state) VALUES(3242, 'Morro Vermelho', 11);
INSERT INTO city(id,name,id_state) VALUES(3243, 'Mucuri', 11);
INSERT INTO city(id,name,id_state) VALUES(3244, 'Mundo Novo de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3245, 'Munhoz', 11);
INSERT INTO city(id,name,id_state) VALUES(3246, 'Muquem', 11);
INSERT INTO city(id,name,id_state) VALUES(3247, 'Muriae', 11);
INSERT INTO city(id,name,id_state) VALUES(3248, 'Mutum', 11);
INSERT INTO city(id,name,id_state) VALUES(3249, 'Muzambinho', 11);
INSERT INTO city(id,name,id_state) VALUES(3250, 'Nacip Raydan', 11);
INSERT INTO city(id,name,id_state) VALUES(3251, 'Nanuque', 11);
INSERT INTO city(id,name,id_state) VALUES(3252, 'Naque', 11);
INSERT INTO city(id,name,id_state) VALUES(3253, 'Naque-Nanuque', 11);
INSERT INTO city(id,name,id_state) VALUES(3254, 'Natercia', 11);
INSERT INTO city(id,name,id_state) VALUES(3255, 'Nazare de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3256, 'Nazareno', 11);
INSERT INTO city(id,name,id_state) VALUES(3257, 'Nelson de Sena', 11);
INSERT INTO city(id,name,id_state) VALUES(3258, 'Neolandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3259, 'Nepomuceno', 11);
INSERT INTO city(id,name,id_state) VALUES(3260, 'Nhandutiba', 11);
INSERT INTO city(id,name,id_state) VALUES(3261, 'Nicolandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3262, 'Nova Belem', 11);
INSERT INTO city(id,name,id_state) VALUES(3263, 'Nova Era', 11);
INSERT INTO city(id,name,id_state) VALUES(3264, 'Nova Esperanca', 11);
INSERT INTO city(id,name,id_state) VALUES(3265, 'Nova Lima', 11);
INSERT INTO city(id,name,id_state) VALUES(3266, 'Nova Minda', 11);
INSERT INTO city(id,name,id_state) VALUES(3267, 'Nova Modica', 11);
INSERT INTO city(id,name,id_state) VALUES(3268, 'Nova Ponte', 11);
INSERT INTO city(id,name,id_state) VALUES(3269, 'Nova Porteirinha', 11);
INSERT INTO city(id,name,id_state) VALUES(3270, 'Nova Resende', 11);
INSERT INTO city(id,name,id_state) VALUES(3271, 'Nova Serrana', 11);
INSERT INTO city(id,name,id_state) VALUES(3272, 'Nova Uniao', 11);
INSERT INTO city(id,name,id_state) VALUES(3273, 'Novilhona', 11);
INSERT INTO city(id,name,id_state) VALUES(3274, 'Novo Cruzeiro', 11);
INSERT INTO city(id,name,id_state) VALUES(3275, 'Novo Horizonte', 11);
INSERT INTO city(id,name,id_state) VALUES(3276, 'Ocidente', 11);
INSERT INTO city(id,name,id_state) VALUES(3277, 'Olaria', 11);
INSERT INTO city(id,name,id_state) VALUES(3278, 'Olegario Maciel', 11);
INSERT INTO city(id,name,id_state) VALUES(3279, 'Olhos D''Agua', 11);
INSERT INTO city(id,name,id_state) VALUES(3280, 'Olhos D''Agua do Oeste', 11);
INSERT INTO city(id,name,id_state) VALUES(3281, 'Olimpio Campos', 11);
INSERT INTO city(id,name,id_state) VALUES(3282, 'Olimpio Noronha', 11);
INSERT INTO city(id,name,id_state) VALUES(3283, 'Oliveira', 11);
INSERT INTO city(id,name,id_state) VALUES(3284, 'Oliveira Fortes', 11);
INSERT INTO city(id,name,id_state) VALUES(3285, 'Onca de Pitangui', 11);
INSERT INTO city(id,name,id_state) VALUES(3286, 'Oratorios', 11);
INSERT INTO city(id,name,id_state) VALUES(3287, 'Orizania', 11);
INSERT INTO city(id,name,id_state) VALUES(3288, 'Ouro Branco', 11);
INSERT INTO city(id,name,id_state) VALUES(3289, 'Ouro Fino', 11);
INSERT INTO city(id,name,id_state) VALUES(3290, 'Ouro Preto', 11);
INSERT INTO city(id,name,id_state) VALUES(3291, 'Ouro Verde de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3292, 'Paciencia', 11);
INSERT INTO city(id,name,id_state) VALUES(3293, 'Padre Brito', 11);
INSERT INTO city(id,name,id_state) VALUES(3294, 'Padre Carvalho', 11);
INSERT INTO city(id,name,id_state) VALUES(3295, 'Padre Felisberto', 11);
INSERT INTO city(id,name,id_state) VALUES(3296, 'Padre Fialho', 11);
INSERT INTO city(id,name,id_state) VALUES(3297, 'Padre Joao Afonso', 11);
INSERT INTO city(id,name,id_state) VALUES(3298, 'Padre Paraiso', 11);
INSERT INTO city(id,name,id_state) VALUES(3299, 'Padre Pinto', 11);
INSERT INTO city(id,name,id_state) VALUES(3300, 'Padre Viegas', 11);
INSERT INTO city(id,name,id_state) VALUES(3301, 'Pai Pedro', 11);
INSERT INTO city(id,name,id_state) VALUES(3302, 'Paineiras', 11);
INSERT INTO city(id,name,id_state) VALUES(3303, 'Pains', 11);
INSERT INTO city(id,name,id_state) VALUES(3304, 'Paiolinho', 11);
INSERT INTO city(id,name,id_state) VALUES(3305, 'Paiva', 11);
INSERT INTO city(id,name,id_state) VALUES(3306, 'Palma', 11);
INSERT INTO city(id,name,id_state) VALUES(3307, 'Palmeiral', 11);
INSERT INTO city(id,name,id_state) VALUES(3308, 'Palmeirinha', 11);
INSERT INTO city(id,name,id_state) VALUES(3309, 'Palmital dos Carvalhos', 11);
INSERT INTO city(id,name,id_state) VALUES(3310, 'Palmopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3311, 'Pantano', 11);
INSERT INTO city(id,name,id_state) VALUES(3312, 'Papagaios', 11);
INSERT INTO city(id,name,id_state) VALUES(3313, 'Para de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3314, 'Paracatu', 11);
INSERT INTO city(id,name,id_state) VALUES(3315, 'Paraguacu', 11);
INSERT INTO city(id,name,id_state) VALUES(3316, 'Paraguai', 11);
INSERT INTO city(id,name,id_state) VALUES(3317, 'Paraiso Garcia', 11);
INSERT INTO city(id,name,id_state) VALUES(3318, 'Paraisopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3319, 'Paraopeba', 11);
INSERT INTO city(id,name,id_state) VALUES(3320, 'Paredao de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3321, 'Parque Durval de Barros', 11);
INSERT INTO city(id,name,id_state) VALUES(3322, 'Parque Industrial', 11);
INSERT INTO city(id,name,id_state) VALUES(3323, 'Passa Dez', 11);
INSERT INTO city(id,name,id_state) VALUES(3324, 'Passa Quatro', 11);
INSERT INTO city(id,name,id_state) VALUES(3325, 'Passa Tempo', 11);
INSERT INTO city(id,name,id_state) VALUES(3326, 'Passa Vinte', 11);
INSERT INTO city(id,name,id_state) VALUES(3327, 'Passabem', 11);
INSERT INTO city(id,name,id_state) VALUES(3328, 'Passagem de Mariana', 11);
INSERT INTO city(id,name,id_state) VALUES(3329, 'Passos', 11);
INSERT INTO city(id,name,id_state) VALUES(3330, 'Patis', 11);
INSERT INTO city(id,name,id_state) VALUES(3331, 'Patos de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3332, 'Patrimonio', 11);
INSERT INTO city(id,name,id_state) VALUES(3333, 'Patrocinio', 11);
INSERT INTO city(id,name,id_state) VALUES(3334, 'Patrocinio do Muriae', 11);
INSERT INTO city(id,name,id_state) VALUES(3335, 'Paula Candido', 11);
INSERT INTO city(id,name,id_state) VALUES(3336, 'Paula Lima', 11);
INSERT INTO city(id,name,id_state) VALUES(3337, 'Paulistas', 11);
INSERT INTO city(id,name,id_state) VALUES(3338, 'Pavao', 11);
INSERT INTO city(id,name,id_state) VALUES(3339, 'Pe do Morro', 11);
INSERT INTO city(id,name,id_state) VALUES(3340, 'Pecanha', 11);
INSERT INTO city(id,name,id_state) VALUES(3341, 'Pedra Azul', 11);
INSERT INTO city(id,name,id_state) VALUES(3342, 'Pedra Bonita', 11);
INSERT INTO city(id,name,id_state) VALUES(3343, 'Pedra Corrida', 11);
INSERT INTO city(id,name,id_state) VALUES(3344, 'Pedra do Anta', 11);
INSERT INTO city(id,name,id_state) VALUES(3345, 'Pedra do Indaia', 11);
INSERT INTO city(id,name,id_state) VALUES(3346, 'Pedra do Sino', 11);
INSERT INTO city(id,name,id_state) VALUES(3347, 'Pedra Dourada', 11);
INSERT INTO city(id,name,id_state) VALUES(3348, 'Pedra Grande', 11);
INSERT INTO city(id,name,id_state) VALUES(3349, 'Pedra Menina', 11);
INSERT INTO city(id,name,id_state) VALUES(3350, 'Pedralva', 11);
INSERT INTO city(id,name,id_state) VALUES(3351, 'Pedras de Maria da Cruz', 11);
INSERT INTO city(id,name,id_state) VALUES(3352, 'Pedrinopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3353, 'Pedro Leopoldo', 11);
INSERT INTO city(id,name,id_state) VALUES(3354, 'Pedro Lessa', 11);
INSERT INTO city(id,name,id_state) VALUES(3355, 'Pedro Teixeira', 11);
INSERT INTO city(id,name,id_state) VALUES(3356, 'Pedro Versiani', 11);
INSERT INTO city(id,name,id_state) VALUES(3357, 'Penedia', 11);
INSERT INTO city(id,name,id_state) VALUES(3358, 'Penha de Franca', 11);
INSERT INTO city(id,name,id_state) VALUES(3359, 'Penha do Capim', 11);
INSERT INTO city(id,name,id_state) VALUES(3360, 'Penha do Cassiano', 11);
INSERT INTO city(id,name,id_state) VALUES(3361, 'Penha do Norte', 11);
INSERT INTO city(id,name,id_state) VALUES(3362, 'Penha Longa', 11);
INSERT INTO city(id,name,id_state) VALUES(3363, 'Pequeri', 11);
INSERT INTO city(id,name,id_state) VALUES(3364, 'Pequi', 11);
INSERT INTO city(id,name,id_state) VALUES(3365, 'Perdigao', 11);
INSERT INTO city(id,name,id_state) VALUES(3366, 'Perdilandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3367, 'Perdizes', 11);
INSERT INTO city(id,name,id_state) VALUES(3368, 'Perdoes', 11);
INSERT INTO city(id,name,id_state) VALUES(3369, 'Pereirinhas', 11);
INSERT INTO city(id,name,id_state) VALUES(3370, 'Periquito', 11);
INSERT INTO city(id,name,id_state) VALUES(3371, 'Perpetuo Socorro', 11);
INSERT INTO city(id,name,id_state) VALUES(3372, 'Pescador', 11);
INSERT INTO city(id,name,id_state) VALUES(3373, 'Petunia', 11);
INSERT INTO city(id,name,id_state) VALUES(3374, 'Piacatuba', 11);
INSERT INTO city(id,name,id_state) VALUES(3375, 'Piao', 11);
INSERT INTO city(id,name,id_state) VALUES(3376, 'Piau', 11);
INSERT INTO city(id,name,id_state) VALUES(3377, 'Pic Sagarana', 11);
INSERT INTO city(id,name,id_state) VALUES(3378, 'Piedade de Ponte Nova', 11);
INSERT INTO city(id,name,id_state) VALUES(3379, 'Piedade do Paraopeba', 11);
INSERT INTO city(id,name,id_state) VALUES(3380, 'Piedade do Rio Grande', 11);
INSERT INTO city(id,name,id_state) VALUES(3381, 'Piedade dos Gerais', 11);
INSERT INTO city(id,name,id_state) VALUES(3382, 'Pilar', 11);
INSERT INTO city(id,name,id_state) VALUES(3383, 'Pimenta', 11);
INSERT INTO city(id,name,id_state) VALUES(3384, 'Pindaibas', 11);
INSERT INTO city(id,name,id_state) VALUES(3385, 'Pinheirinhos', 11);
INSERT INTO city(id,name,id_state) VALUES(3386, 'Pinheiros Altos', 11);
INSERT INTO city(id,name,id_state) VALUES(3387, 'Pinhotiba', 11);
INSERT INTO city(id,name,id_state) VALUES(3388, 'Pintos Negreiros', 11);
INSERT INTO city(id,name,id_state) VALUES(3389, 'Piracaiba', 11);
INSERT INTO city(id,name,id_state) VALUES(3390, 'Piracema', 11);
INSERT INTO city(id,name,id_state) VALUES(3391, 'Pirajuba', 11);
INSERT INTO city(id,name,id_state) VALUES(3392, 'Piranga', 11);
INSERT INTO city(id,name,id_state) VALUES(3393, 'Pirangucu', 11);
INSERT INTO city(id,name,id_state) VALUES(3394, 'Piranguinho', 11);
INSERT INTO city(id,name,id_state) VALUES(3395, 'Piranguita', 11);
INSERT INTO city(id,name,id_state) VALUES(3396, 'Pirapanema', 11);
INSERT INTO city(id,name,id_state) VALUES(3397, 'Pirapetinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3398, 'Pirapora', 11);
INSERT INTO city(id,name,id_state) VALUES(3399, 'Pirauba', 11);
INSERT INTO city(id,name,id_state) VALUES(3400, 'Pires e Albuquerque', 11);
INSERT INTO city(id,name,id_state) VALUES(3401, 'Piscamba', 11);
INSERT INTO city(id,name,id_state) VALUES(3402, 'Pitangui', 11);
INSERT INTO city(id,name,id_state) VALUES(3403, 'Pitarana', 11);
INSERT INTO city(id,name,id_state) VALUES(3404, 'Piui', 11);
INSERT INTO city(id,name,id_state) VALUES(3405, 'Planalto de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3406, 'Planura', 11);
INSERT INTO city(id,name,id_state) VALUES(3407, 'Plautino Soares', 11);
INSERT INTO city(id,name,id_state) VALUES(3408, 'Poaia', 11);
INSERT INTO city(id,name,id_state) VALUES(3409, 'Poco Fundo', 11);
INSERT INTO city(id,name,id_state) VALUES(3410, 'Pocoes de Paineiras', 11);
INSERT INTO city(id,name,id_state) VALUES(3411, 'Pocos de Caldas', 11);
INSERT INTO city(id,name,id_state) VALUES(3412, 'Pocrane', 11);
INSERT INTO city(id,name,id_state) VALUES(3413, 'Pompeu', 11);
INSERT INTO city(id,name,id_state) VALUES(3414, 'Poncianos', 11);
INSERT INTO city(id,name,id_state) VALUES(3415, 'Pontalete', 11);
INSERT INTO city(id,name,id_state) VALUES(3416, 'Ponte Alta', 11);
INSERT INTO city(id,name,id_state) VALUES(3417, 'Ponte Alta de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3418, 'Ponte dos Ciganos', 11);
INSERT INTO city(id,name,id_state) VALUES(3419, 'Ponte Firme', 11);
INSERT INTO city(id,name,id_state) VALUES(3420, 'Ponte Nova', 11);
INSERT INTO city(id,name,id_state) VALUES(3421, 'Ponte Segura', 11);
INSERT INTO city(id,name,id_state) VALUES(3422, 'Pontevila', 11);
INSERT INTO city(id,name,id_state) VALUES(3423, 'Ponto Chique', 11);
INSERT INTO city(id,name,id_state) VALUES(3424, 'Ponto do Marambaia', 11);
INSERT INTO city(id,name,id_state) VALUES(3425, 'Ponto dos Volantes', 11);
INSERT INTO city(id,name,id_state) VALUES(3426, 'Porteirinha', 11);
INSERT INTO city(id,name,id_state) VALUES(3427, 'Porto Agrario', 11);
INSERT INTO city(id,name,id_state) VALUES(3428, 'Porto das Flores', 11);
INSERT INTO city(id,name,id_state) VALUES(3429, 'Porto dos Mendes', 11);
INSERT INTO city(id,name,id_state) VALUES(3430, 'Porto Firme', 11);
INSERT INTO city(id,name,id_state) VALUES(3431, 'Pote', 11);
INSERT INTO city(id,name,id_state) VALUES(3432, 'Pouso Alegre', 11);
INSERT INTO city(id,name,id_state) VALUES(3433, 'Pouso Alto', 11);
INSERT INTO city(id,name,id_state) VALUES(3434, 'Prados', 11);
INSERT INTO city(id,name,id_state) VALUES(3435, 'Prata', 11);
INSERT INTO city(id,name,id_state) VALUES(3436, 'Pratapolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3437, 'Pratinha', 11);
INSERT INTO city(id,name,id_state) VALUES(3438, 'Presidente Bernardes', 11);
INSERT INTO city(id,name,id_state) VALUES(3439, 'Presidente Juscelino', 11);
INSERT INTO city(id,name,id_state) VALUES(3440, 'Presidente Kubitschek', 11);
INSERT INTO city(id,name,id_state) VALUES(3441, 'Presidente Olegario', 11);
INSERT INTO city(id,name,id_state) VALUES(3442, 'Presidente Pena', 11);
INSERT INTO city(id,name,id_state) VALUES(3443, 'Professor Sperber', 11);
INSERT INTO city(id,name,id_state) VALUES(3444, 'Providencia', 11);
INSERT INTO city(id,name,id_state) VALUES(3445, 'Prudente de Morais', 11);
INSERT INTO city(id,name,id_state) VALUES(3446, 'Quartel de Sao Joao', 11);
INSERT INTO city(id,name,id_state) VALUES(3447, 'Quartel do Sacramento', 11);
INSERT INTO city(id,name,id_state) VALUES(3448, 'Quartel Geral', 11);
INSERT INTO city(id,name,id_state) VALUES(3449, 'Quatituba', 11);
INSERT INTO city(id,name,id_state) VALUES(3450, 'Queixada', 11);
INSERT INTO city(id,name,id_state) VALUES(3451, 'Queluzita', 11);
INSERT INTO city(id,name,id_state) VALUES(3452, 'Quem-Quem', 11);
INSERT INTO city(id,name,id_state) VALUES(3453, 'Quilombo', 11);
INSERT INTO city(id,name,id_state) VALUES(3454, 'Quintinos', 11);
INSERT INTO city(id,name,id_state) VALUES(3455, 'Raposos', 11);
INSERT INTO city(id,name,id_state) VALUES(3456, 'Raul Soares', 11);
INSERT INTO city(id,name,id_state) VALUES(3457, 'Ravena', 11);
INSERT INTO city(id,name,id_state) VALUES(3458, 'Realeza', 11);
INSERT INTO city(id,name,id_state) VALUES(3459, 'Recreio', 11);
INSERT INTO city(id,name,id_state) VALUES(3460, 'Reduto', 11);
INSERT INTO city(id,name,id_state) VALUES(3461, 'Resende Costa', 11);
INSERT INTO city(id,name,id_state) VALUES(3462, 'Resplendor', 11);
INSERT INTO city(id,name,id_state) VALUES(3463, 'Ressaquinha', 11);
INSERT INTO city(id,name,id_state) VALUES(3464, 'Riachinho', 11);
INSERT INTO city(id,name,id_state) VALUES(3465, 'Riacho da Cruz', 11);
INSERT INTO city(id,name,id_state) VALUES(3466, 'Riacho dos Machados', 11);
INSERT INTO city(id,name,id_state) VALUES(3467, 'Ribeirao das Neves', 11);
INSERT INTO city(id,name,id_state) VALUES(3468, 'Ribeirao de Sao Domingos', 11);
INSERT INTO city(id,name,id_state) VALUES(3469, 'Ribeirao Vermelho', 11);
INSERT INTO city(id,name,id_state) VALUES(3470, 'Ribeiro Junqueira', 11);
INSERT INTO city(id,name,id_state) VALUES(3471, 'Ribeiros', 11);
INSERT INTO city(id,name,id_state) VALUES(3472, 'Rio Acima', 11);
INSERT INTO city(id,name,id_state) VALUES(3473, 'Rio Casca', 11);
INSERT INTO city(id,name,id_state) VALUES(3474, 'Rio das Mortes', 11);
INSERT INTO city(id,name,id_state) VALUES(3475, 'Rio do Prado', 11);
INSERT INTO city(id,name,id_state) VALUES(3476, 'Rio Doce', 11);
INSERT INTO city(id,name,id_state) VALUES(3477, 'Rio Espera', 11);
INSERT INTO city(id,name,id_state) VALUES(3478, 'Rio Manso', 11);
INSERT INTO city(id,name,id_state) VALUES(3479, 'Rio Melo', 11);
INSERT INTO city(id,name,id_state) VALUES(3480, 'Rio Novo', 11);
INSERT INTO city(id,name,id_state) VALUES(3481, 'Rio Paranaiba', 11);
INSERT INTO city(id,name,id_state) VALUES(3482, 'Rio Pardo de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3483, 'Rio Piracicaba', 11);
INSERT INTO city(id,name,id_state) VALUES(3484, 'Rio Pomba', 11);
INSERT INTO city(id,name,id_state) VALUES(3485, 'Rio Pretinho', 11);
INSERT INTO city(id,name,id_state) VALUES(3486, 'Rio Preto', 11);
INSERT INTO city(id,name,id_state) VALUES(3487, 'Rio Vermelho', 11);
INSERT INTO city(id,name,id_state) VALUES(3488, 'Ritapolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3489, 'Roca Grande', 11);
INSERT INTO city(id,name,id_state) VALUES(3490, 'Rocas Novas', 11);
INSERT INTO city(id,name,id_state) VALUES(3491, 'Rochedo de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3492, 'Rodeador', 11);
INSERT INTO city(id,name,id_state) VALUES(3493, 'Rodeiro', 11);
INSERT INTO city(id,name,id_state) VALUES(3494, 'Rodrigo Silva', 11);
INSERT INTO city(id,name,id_state) VALUES(3495, 'Romaria', 11);
INSERT INTO city(id,name,id_state) VALUES(3496, 'Rosario da Limeira', 11);
INSERT INTO city(id,name,id_state) VALUES(3497, 'Rosario de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3498, 'Rosario do Pontal', 11);
INSERT INTO city(id,name,id_state) VALUES(3499, 'Roseiral', 11);
INSERT INTO city(id,name,id_state) VALUES(3500, 'Rubelita', 11);
INSERT INTO city(id,name,id_state) VALUES(3501, 'Rubim', 11);
INSERT INTO city(id,name,id_state) VALUES(3502, 'Sabara', 11);
INSERT INTO city(id,name,id_state) VALUES(3503, 'Sabinopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3504, 'Sacramento', 11);
INSERT INTO city(id,name,id_state) VALUES(3505, 'Salinas', 11);
INSERT INTO city(id,name,id_state) VALUES(3506, 'Salitre de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3507, 'Salto da Divisa', 11);
INSERT INTO city(id,name,id_state) VALUES(3508, 'Sanatorio Santa Fe', 11);
INSERT INTO city(id,name,id_state) VALUES(3509, 'Santa Barbara', 11);
INSERT INTO city(id,name,id_state) VALUES(3510, 'Santa Barbara do Leste', 11);
INSERT INTO city(id,name,id_state) VALUES(3511, 'Santa Barbara do Monte Verde', 11);
INSERT INTO city(id,name,id_state) VALUES(3512, 'Santa Barbara do Tugurio', 11);
INSERT INTO city(id,name,id_state) VALUES(3513, 'Santa Cruz da Aparecida', 11);
INSERT INTO city(id,name,id_state) VALUES(3514, 'Santa Cruz de Botumirim', 11);
INSERT INTO city(id,name,id_state) VALUES(3515, 'Santa Cruz de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3516, 'Santa Cruz de Salinas', 11);
INSERT INTO city(id,name,id_state) VALUES(3517, 'Santa Cruz do Escalvado', 11);
INSERT INTO city(id,name,id_state) VALUES(3518, 'Santa Cruz do Prata', 11);
INSERT INTO city(id,name,id_state) VALUES(3519, 'Santa Efigenia', 11);
INSERT INTO city(id,name,id_state) VALUES(3520, 'Santa Efigenia de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3521, 'Santa Fe de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3522, 'Santa Filomena', 11);
INSERT INTO city(id,name,id_state) VALUES(3523, 'Santa Isabel', 11);
INSERT INTO city(id,name,id_state) VALUES(3524, 'Santa Juliana', 11);
INSERT INTO city(id,name,id_state) VALUES(3525, 'Santa Luzia', 11);
INSERT INTO city(id,name,id_state) VALUES(3526, 'Santa Luzia da Serra', 11);
INSERT INTO city(id,name,id_state) VALUES(3527, 'Santa Margarida', 11);
INSERT INTO city(id,name,id_state) VALUES(3528, 'Santa Maria de Itabira', 11);
INSERT INTO city(id,name,id_state) VALUES(3529, 'Santa Maria do Salto', 11);
INSERT INTO city(id,name,id_state) VALUES(3530, 'Santa Maria do Suacui', 11);
INSERT INTO city(id,name,id_state) VALUES(3531, 'Santa Rita da Estrela', 11);
INSERT INTO city(id,name,id_state) VALUES(3532, 'Santa Rita de Caldas', 11);
INSERT INTO city(id,name,id_state) VALUES(3533, 'Santa Rita de Jacutinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3534, 'Santa Rita de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3535, 'Santa Rita de Ouro Preto', 11);
INSERT INTO city(id,name,id_state) VALUES(3536, 'Santa Rita do Cedro', 11);
INSERT INTO city(id,name,id_state) VALUES(3537, 'Santa Rita do Ibitipoca', 11);
INSERT INTO city(id,name,id_state) VALUES(3538, 'Santa Rita do Itueto', 11);
INSERT INTO city(id,name,id_state) VALUES(3539, 'Santa Rita do Rio do Peixe', 11);
INSERT INTO city(id,name,id_state) VALUES(3540, 'Santa Rita do Sapucai', 11);
INSERT INTO city(id,name,id_state) VALUES(3541, 'Santa Rita Durao', 11);
INSERT INTO city(id,name,id_state) VALUES(3542, 'Santa Rosa da Serra', 11);
INSERT INTO city(id,name,id_state) VALUES(3543, 'Santa Rosa de Lima', 11);
INSERT INTO city(id,name,id_state) VALUES(3544, 'Santa Rosa dos Dourados', 11);
INSERT INTO city(id,name,id_state) VALUES(3545, 'Santa Teresa do Bonito', 11);
INSERT INTO city(id,name,id_state) VALUES(3546, 'Santa Terezinha de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3547, 'Santa Vitoria', 11);
INSERT INTO city(id,name,id_state) VALUES(3548, 'Santana da Vargem', 11);
INSERT INTO city(id,name,id_state) VALUES(3549, 'Santana de Caldas', 11);
INSERT INTO city(id,name,id_state) VALUES(3550, 'Santana de Cataguases', 11);
INSERT INTO city(id,name,id_state) VALUES(3551, 'Santana de Patos', 11);
INSERT INTO city(id,name,id_state) VALUES(3552, 'Santana de Pirapama', 11);
INSERT INTO city(id,name,id_state) VALUES(3553, 'Santana do Alfie', 11);
INSERT INTO city(id,name,id_state) VALUES(3554, 'Santana do Aracuai', 11);
INSERT INTO city(id,name,id_state) VALUES(3555, 'Santana do Campestre', 11);
INSERT INTO city(id,name,id_state) VALUES(3556, 'Santana do Capivari', 11);
INSERT INTO city(id,name,id_state) VALUES(3557, 'Santana do Deserto', 11);
INSERT INTO city(id,name,id_state) VALUES(3558, 'Santana do Garambeu', 11);
INSERT INTO city(id,name,id_state) VALUES(3559, 'Santana do Jacare', 11);
INSERT INTO city(id,name,id_state) VALUES(3560, 'Santana do Manhuacu', 11);
INSERT INTO city(id,name,id_state) VALUES(3561, 'Santana do Paraiso', 11);
INSERT INTO city(id,name,id_state) VALUES(3562, 'Santana do Paraopeba', 11);
INSERT INTO city(id,name,id_state) VALUES(3563, 'Santana do Riacho', 11);
INSERT INTO city(id,name,id_state) VALUES(3564, 'Santana do Tabuleiro', 11);
INSERT INTO city(id,name,id_state) VALUES(3565, 'Santana dos Montes', 11);
INSERT INTO city(id,name,id_state) VALUES(3566, 'Santo Antonio da Boa Vista', 11);
INSERT INTO city(id,name,id_state) VALUES(3567, 'Santo Antonio da Fortaleza', 11);
INSERT INTO city(id,name,id_state) VALUES(3568, 'Santo Antonio da Vargem Alegre', 11);
INSERT INTO city(id,name,id_state) VALUES(3569, 'Santo Antonio do Amparo', 11);
INSERT INTO city(id,name,id_state) VALUES(3570, 'Santo Antonio do Aventureiro', 11);
INSERT INTO city(id,name,id_state) VALUES(3571, 'Santo Antonio do Boqueirao', 11);
INSERT INTO city(id,name,id_state) VALUES(3572, 'Santo Antonio do Cruzeiro', 11);
INSERT INTO city(id,name,id_state) VALUES(3573, 'Santo Antonio do Gloria', 11);
INSERT INTO city(id,name,id_state) VALUES(3574, 'Santo Antonio do Grama', 11);
INSERT INTO city(id,name,id_state) VALUES(3575, 'Santo Antonio do Itambe', 11);
INSERT INTO city(id,name,id_state) VALUES(3576, 'Santo Antonio do Jacinto', 11);
INSERT INTO city(id,name,id_state) VALUES(3577, 'Santo Antonio do Leite', 11);
INSERT INTO city(id,name,id_state) VALUES(3578, 'Santo Antonio do Manhuacu', 11);
INSERT INTO city(id,name,id_state) VALUES(3579, 'Santo Antonio do Monte', 11);
INSERT INTO city(id,name,id_state) VALUES(3580, 'Santo Antonio do Mucuri', 11);
INSERT INTO city(id,name,id_state) VALUES(3581, 'Santo Antonio do Norte', 11);
INSERT INTO city(id,name,id_state) VALUES(3582, 'Santo Antonio do Pirapetinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3583, 'Santo Antonio do Retiro', 11);
INSERT INTO city(id,name,id_state) VALUES(3584, 'Santo Antonio do Rio Abaixo', 11);
INSERT INTO city(id,name,id_state) VALUES(3585, 'Santo Antonio dos Araujos', 11);
INSERT INTO city(id,name,id_state) VALUES(3586, 'Santo Antonio dos Campos', 11);
INSERT INTO city(id,name,id_state) VALUES(3587, 'Santo Hilario', 11);
INSERT INTO city(id,name,id_state) VALUES(3588, 'Santo Hipolito', 11);
INSERT INTO city(id,name,id_state) VALUES(3589, 'Santos Dumont', 11);
INSERT INTO city(id,name,id_state) VALUES(3590, 'Sao Bartolomeu', 11);
INSERT INTO city(id,name,id_state) VALUES(3591, 'Sao Benedito', 11);
INSERT INTO city(id,name,id_state) VALUES(3592, 'Sao Bento Abade', 11);
INSERT INTO city(id,name,id_state) VALUES(3593, 'Sao Bento de Caldas', 11);
INSERT INTO city(id,name,id_state) VALUES(3594, 'Sao Bras do Suacui', 11);
INSERT INTO city(id,name,id_state) VALUES(3595, 'Sao Braz', 11);
INSERT INTO city(id,name,id_state) VALUES(3596, 'Sao Candido', 11);
INSERT INTO city(id,name,id_state) VALUES(3597, 'Sao Domingos', 11);
INSERT INTO city(id,name,id_state) VALUES(3598, 'Sao Domingos da Bocaina', 11);
INSERT INTO city(id,name,id_state) VALUES(3599, 'Sao Domingos das Dores', 11);
INSERT INTO city(id,name,id_state) VALUES(3600, 'Sao Domingos do Prata', 11);
INSERT INTO city(id,name,id_state) VALUES(3601, 'Sao Francisco', 11);
INSERT INTO city(id,name,id_state) VALUES(3602, 'Sao Francisco de Paula', 11);
INSERT INTO city(id,name,id_state) VALUES(3603, 'Sao Francisco de Sales', 11);
INSERT INTO city(id,name,id_state) VALUES(3604, 'Sao Francisco do Gloria', 11);
INSERT INTO city(id,name,id_state) VALUES(3605, 'Sao Francisco do Humaita', 11);
INSERT INTO city(id,name,id_state) VALUES(3606, 'Sao Geraldo', 11);
INSERT INTO city(id,name,id_state) VALUES(3607, 'Sao Geraldo da Piedade', 11);
INSERT INTO city(id,name,id_state) VALUES(3608, 'Sao Geraldo de Tumiritinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3609, 'Sao Geraldo do Baguari', 11);
INSERT INTO city(id,name,id_state) VALUES(3610, 'Sao Geraldo do Baixio', 11);
INSERT INTO city(id,name,id_state) VALUES(3611, 'Sao Goncalo de Botelhos', 11);
INSERT INTO city(id,name,id_state) VALUES(3612, 'Sao Goncalo do Abaete', 11);
INSERT INTO city(id,name,id_state) VALUES(3613, 'Sao Goncalo do Monte', 11);
INSERT INTO city(id,name,id_state) VALUES(3614, 'Sao Goncalo do Para', 11);
INSERT INTO city(id,name,id_state) VALUES(3615, 'Sao Goncalo do Rio Abaixo', 11);
INSERT INTO city(id,name,id_state) VALUES(3616, 'Sao Goncalo do Rio das Pedras', 11);
INSERT INTO city(id,name,id_state) VALUES(3617, 'Sao Goncalo do Rio Preto', 11);
INSERT INTO city(id,name,id_state) VALUES(3618, 'Sao Goncalo do Sapucai', 11);
INSERT INTO city(id,name,id_state) VALUES(3619, 'Sao Gotardo', 11);
INSERT INTO city(id,name,id_state) VALUES(3620, 'Sao Jeronimo dos Pocoes', 11);
INSERT INTO city(id,name,id_state) VALUES(3621, 'Sao Joao Batista do Gloria', 11);
INSERT INTO city(id,name,id_state) VALUES(3622, 'Sao Joao da Chapada', 11);
INSERT INTO city(id,name,id_state) VALUES(3623, 'Sao Joao da Lagoa', 11);
INSERT INTO city(id,name,id_state) VALUES(3624, 'Sao Joao da Mata', 11);
INSERT INTO city(id,name,id_state) VALUES(3625, 'Sao Joao da Ponte', 11);
INSERT INTO city(id,name,id_state) VALUES(3626, 'Sao Joao da Sapucaia', 11);
INSERT INTO city(id,name,id_state) VALUES(3627, 'Sao Joao da Serra', 11);
INSERT INTO city(id,name,id_state) VALUES(3628, 'Sao Joao da Serra Negra', 11);
INSERT INTO city(id,name,id_state) VALUES(3629, 'Sao Joao da Vereda', 11);
INSERT INTO city(id,name,id_state) VALUES(3630, 'Sao Joao del Rei', 11);
INSERT INTO city(id,name,id_state) VALUES(3631, 'Sao Joao do Bonito', 11);
INSERT INTO city(id,name,id_state) VALUES(3632, 'Sao Joao do Jacutinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3633, 'Sao Joao do Manhuacu', 11);
INSERT INTO city(id,name,id_state) VALUES(3634, 'Sao Joao do Manteninha', 11);
INSERT INTO city(id,name,id_state) VALUES(3635, 'Sao Joao do Oriente', 11);
INSERT INTO city(id,name,id_state) VALUES(3636, 'Sao Joao do Pacui', 11);
INSERT INTO city(id,name,id_state) VALUES(3637, 'Sao Joao do Paraiso', 11);
INSERT INTO city(id,name,id_state) VALUES(3638, 'Sao Joao Evangelista', 11);
INSERT INTO city(id,name,id_state) VALUES(3639, 'Sao Joao Nepomuceno', 11);
INSERT INTO city(id,name,id_state) VALUES(3640, 'Sao Joaquim', 11);
INSERT INTO city(id,name,id_state) VALUES(3641, 'Sao Joaquim de Bicas', 11);
INSERT INTO city(id,name,id_state) VALUES(3642, 'Sao Jose da Barra', 11);
INSERT INTO city(id,name,id_state) VALUES(3643, 'Sao Jose da Bela Vista', 11);
INSERT INTO city(id,name,id_state) VALUES(3644, 'Sao Jose da Lapa', 11);
INSERT INTO city(id,name,id_state) VALUES(3645, 'Sao Jose da Pedra Menina', 11);
INSERT INTO city(id,name,id_state) VALUES(3646, 'Sao Jose da Safira', 11);
INSERT INTO city(id,name,id_state) VALUES(3647, 'Sao Jose da Varginha', 11);
INSERT INTO city(id,name,id_state) VALUES(3648, 'Sao Jose das Tronqueiras', 11);
INSERT INTO city(id,name,id_state) VALUES(3649, 'Sao Jose do Acacio', 11);
INSERT INTO city(id,name,id_state) VALUES(3650, 'Sao Jose do Alegre', 11);
INSERT INTO city(id,name,id_state) VALUES(3651, 'Sao Jose do Barreiro', 11);
INSERT INTO city(id,name,id_state) VALUES(3652, 'Sao Jose do Batatal', 11);
INSERT INTO city(id,name,id_state) VALUES(3653, 'Sao Jose do Buriti', 11);
INSERT INTO city(id,name,id_state) VALUES(3654, 'Sao Jose do Divino', 11);
INSERT INTO city(id,name,id_state) VALUES(3655, 'Sao Jose do Goiabal', 11);
INSERT INTO city(id,name,id_state) VALUES(3656, 'Sao Jose do Itueto', 11);
INSERT INTO city(id,name,id_state) VALUES(3657, 'Sao Jose do Jacuri', 11);
INSERT INTO city(id,name,id_state) VALUES(3658, 'Sao Jose do Mantimento', 11);
INSERT INTO city(id,name,id_state) VALUES(3659, 'Sao Jose do Mato Dentro', 11);
INSERT INTO city(id,name,id_state) VALUES(3660, 'Sao Jose do Pantano', 11);
INSERT INTO city(id,name,id_state) VALUES(3661, 'Sao Jose do Paraopeba', 11);
INSERT INTO city(id,name,id_state) VALUES(3662, 'Sao Jose dos Lopes', 11);
INSERT INTO city(id,name,id_state) VALUES(3663, 'Sao Jose dos Salgados', 11);
INSERT INTO city(id,name,id_state) VALUES(3664, 'Sao Lourenco', 11);
INSERT INTO city(id,name,id_state) VALUES(3665, 'Sao Manoel do Guaiacu', 11);
INSERT INTO city(id,name,id_state) VALUES(3666, 'Sao Mateus de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3667, 'Sao Miguel do Anta', 11);
INSERT INTO city(id,name,id_state) VALUES(3668, 'Sao Pedro da Garca', 11);
INSERT INTO city(id,name,id_state) VALUES(3669, 'Sao Pedro da Uniao', 11);
INSERT INTO city(id,name,id_state) VALUES(3670, 'Sao Pedro das Tabocas', 11);
INSERT INTO city(id,name,id_state) VALUES(3671, 'Sao Pedro de Caldas', 11);
INSERT INTO city(id,name,id_state) VALUES(3672, 'Sao Pedro do Avai', 11);
INSERT INTO city(id,name,id_state) VALUES(3673, 'Sao Pedro do Gloria', 11);
INSERT INTO city(id,name,id_state) VALUES(3674, 'Sao Pedro do Jequitinhonha', 11);
INSERT INTO city(id,name,id_state) VALUES(3675, 'Sao Pedro do Suacui', 11);
INSERT INTO city(id,name,id_state) VALUES(3676, 'Sao Pedro dos Ferros', 11);
INSERT INTO city(id,name,id_state) VALUES(3677, 'Sao Roberto', 11);
INSERT INTO city(id,name,id_state) VALUES(3678, 'Sao Romao', 11);
INSERT INTO city(id,name,id_state) VALUES(3679, 'Sao Roque de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3680, 'Sao Sebastiao da Anta', 11);
INSERT INTO city(id,name,id_state) VALUES(3681, 'Sao Sebastiao da Barra', 11);
INSERT INTO city(id,name,id_state) VALUES(3682, 'Sao Sebastiao da Bela Vista', 11);
INSERT INTO city(id,name,id_state) VALUES(3683, 'Sao Sebastiao da Vala', 11);
INSERT INTO city(id,name,id_state) VALUES(3684, 'Sao Sebastiao da Vargem Alegre', 11);
INSERT INTO city(id,name,id_state) VALUES(3685, 'Sao Sebastiao da Vitoria', 11);
INSERT INTO city(id,name,id_state) VALUES(3686, 'Sao Sebastiao do Baixio', 11);
INSERT INTO city(id,name,id_state) VALUES(3687, 'Sao Sebastiao do Barreado', 11);
INSERT INTO city(id,name,id_state) VALUES(3688, 'Sao Sebastiao do Barreiro', 11);
INSERT INTO city(id,name,id_state) VALUES(3689, 'Sao Sebastiao do Bonsucesso', 11);
INSERT INTO city(id,name,id_state) VALUES(3690, 'Sao Sebastiao do Bugre', 11);
INSERT INTO city(id,name,id_state) VALUES(3691, 'Sao Sebastiao do Gil', 11);
INSERT INTO city(id,name,id_state) VALUES(3692, 'Sao Sebastiao do Maranhao', 11);
INSERT INTO city(id,name,id_state) VALUES(3693, 'Sao Sebastiao do Oculo', 11);
INSERT INTO city(id,name,id_state) VALUES(3694, 'Sao Sebastiao do Oeste', 11);
INSERT INTO city(id,name,id_state) VALUES(3695, 'Sao Sebastiao do Paraiso', 11);
INSERT INTO city(id,name,id_state) VALUES(3696, 'Sao Sebastiao do Pontal', 11);
INSERT INTO city(id,name,id_state) VALUES(3697, 'Sao Sebastiao do Rio Preto', 11);
INSERT INTO city(id,name,id_state) VALUES(3698, 'Sao Sebastiao do Rio Verde', 11);
INSERT INTO city(id,name,id_state) VALUES(3699, 'Sao Sebastiao do Sacramento', 11);
INSERT INTO city(id,name,id_state) VALUES(3700, 'Sao Sebastiao do Soberbo', 11);
INSERT INTO city(id,name,id_state) VALUES(3701, 'Sao Sebastiao dos Pocoes', 11);
INSERT INTO city(id,name,id_state) VALUES(3702, 'Sao Sebastiao dos Robertos', 11);
INSERT INTO city(id,name,id_state) VALUES(3703, 'Sao Tiago', 11);
INSERT INTO city(id,name,id_state) VALUES(3704, 'Sao Tomas de Aquino', 11);
INSERT INTO city(id,name,id_state) VALUES(3705, 'Sao Tome das Letras', 11);
INSERT INTO city(id,name,id_state) VALUES(3706, 'Sao Vicente', 11);
INSERT INTO city(id,name,id_state) VALUES(3707, 'Sao Vicente da Estrela', 11);
INSERT INTO city(id,name,id_state) VALUES(3708, 'Sao Vicente de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3709, 'Sao Vicente do Grama', 11);
INSERT INTO city(id,name,id_state) VALUES(3710, 'Sao Vicente do Rio Doce', 11);
INSERT INTO city(id,name,id_state) VALUES(3711, 'Sao Vitor', 11);
INSERT INTO city(id,name,id_state) VALUES(3712, 'Sapucai', 11);
INSERT INTO city(id,name,id_state) VALUES(3713, 'Sapucai-Mirim', 11);
INSERT INTO city(id,name,id_state) VALUES(3714, 'Sapucaia', 11);
INSERT INTO city(id,name,id_state) VALUES(3715, 'Sapucaia de Guanhaes', 11);
INSERT INTO city(id,name,id_state) VALUES(3716, 'Sapucaia do Norte', 11);
INSERT INTO city(id,name,id_state) VALUES(3717, 'Sarandira', 11);
INSERT INTO city(id,name,id_state) VALUES(3718, 'Sardoa', 11);
INSERT INTO city(id,name,id_state) VALUES(3719, 'Sarzedo', 11);
INSERT INTO city(id,name,id_state) VALUES(3720, 'Saudade', 11);
INSERT INTO city(id,name,id_state) VALUES(3721, 'Sem Peixe', 11);
INSERT INTO city(id,name,id_state) VALUES(3722, 'Senador Amaral', 11);
INSERT INTO city(id,name,id_state) VALUES(3723, 'Senador Cortes', 11);
INSERT INTO city(id,name,id_state) VALUES(3724, 'Senador Firmino', 11);
INSERT INTO city(id,name,id_state) VALUES(3725, 'Senador Jose Bento', 11);
INSERT INTO city(id,name,id_state) VALUES(3726, 'Senador Melo Viana', 11);
INSERT INTO city(id,name,id_state) VALUES(3727, 'Senador Modestino Goncalves', 11);
INSERT INTO city(id,name,id_state) VALUES(3728, 'Senador Mourao', 11);
INSERT INTO city(id,name,id_state) VALUES(3729, 'Senhora da Gloria', 11);
INSERT INTO city(id,name,id_state) VALUES(3730, 'Senhora da Penha', 11);
INSERT INTO city(id,name,id_state) VALUES(3731, 'Senhora das Dores', 11);
INSERT INTO city(id,name,id_state) VALUES(3732, 'Senhora de Oliveira', 11);
INSERT INTO city(id,name,id_state) VALUES(3733, 'Senhora do Carmo', 11);
INSERT INTO city(id,name,id_state) VALUES(3734, 'Senhora do Porto', 11);
INSERT INTO city(id,name,id_state) VALUES(3735, 'Senhora dos Remedios', 11);
INSERT INTO city(id,name,id_state) VALUES(3736, 'Sereno', 11);
INSERT INTO city(id,name,id_state) VALUES(3737, 'Sericita', 11);
INSERT INTO city(id,name,id_state) VALUES(3738, 'Seritinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3739, 'Serra Azul', 11);
INSERT INTO city(id,name,id_state) VALUES(3740, 'Serra Azul de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3741, 'Serra Bonita', 11);
INSERT INTO city(id,name,id_state) VALUES(3742, 'Serra da Canastra', 11);
INSERT INTO city(id,name,id_state) VALUES(3743, 'Serra da Saudade', 11);
INSERT INTO city(id,name,id_state) VALUES(3744, 'Serra das Araras', 11);
INSERT INTO city(id,name,id_state) VALUES(3745, 'Serra do Camapua', 11);
INSERT INTO city(id,name,id_state) VALUES(3746, 'Serra do Salitre', 11);
INSERT INTO city(id,name,id_state) VALUES(3747, 'Serra dos Aimores', 11);
INSERT INTO city(id,name,id_state) VALUES(3748, 'Serra dos Lemes', 11);
INSERT INTO city(id,name,id_state) VALUES(3749, 'Serra Nova', 11);
INSERT INTO city(id,name,id_state) VALUES(3750, 'Serrania', 11);
INSERT INTO city(id,name,id_state) VALUES(3751, 'Serranopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3752, 'Serranos', 11);
INSERT INTO city(id,name,id_state) VALUES(3753, 'Serro', 11);
INSERT INTO city(id,name,id_state) VALUES(3754, 'Sertaozinho', 11);
INSERT INTO city(id,name,id_state) VALUES(3755, 'Sete Cachoeiras', 11);
INSERT INTO city(id,name,id_state) VALUES(3756, 'Sete Lagoas', 11);
INSERT INTO city(id,name,id_state) VALUES(3757, 'Setubinha', 11);
INSERT INTO city(id,name,id_state) VALUES(3758, 'Silva Campos', 11);
INSERT INTO city(id,name,id_state) VALUES(3759, 'Silva Xavier', 11);
INSERT INTO city(id,name,id_state) VALUES(3760, 'Silvano', 11);
INSERT INTO city(id,name,id_state) VALUES(3761, 'Silveira Carvalho', 11);
INSERT INTO city(id,name,id_state) VALUES(3762, 'Silveirania', 11);
INSERT INTO city(id,name,id_state) VALUES(3763, 'Silvestre', 11);
INSERT INTO city(id,name,id_state) VALUES(3764, 'Silvianopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3765, 'Simao Campos', 11);
INSERT INTO city(id,name,id_state) VALUES(3766, 'Simao Pereira', 11);
INSERT INTO city(id,name,id_state) VALUES(3767, 'Simonesia', 11);
INSERT INTO city(id,name,id_state) VALUES(3768, 'Sobral Pinto', 11);
INSERT INTO city(id,name,id_state) VALUES(3769, 'Sobralia', 11);
INSERT INTO city(id,name,id_state) VALUES(3770, 'Soledade de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3771, 'Sopa', 11);
INSERT INTO city(id,name,id_state) VALUES(3772, 'Tabajara', 11);
INSERT INTO city(id,name,id_state) VALUES(3773, 'Tabauna', 11);
INSERT INTO city(id,name,id_state) VALUES(3774, 'Tabuao', 11);
INSERT INTO city(id,name,id_state) VALUES(3775, 'Tabuleiro', 11);
INSERT INTO city(id,name,id_state) VALUES(3776, 'Taiobeiras', 11);
INSERT INTO city(id,name,id_state) VALUES(3777, 'Taparuba', 11);
INSERT INTO city(id,name,id_state) VALUES(3778, 'Tapira', 11);
INSERT INTO city(id,name,id_state) VALUES(3779, 'Tapirai', 11);
INSERT INTO city(id,name,id_state) VALUES(3780, 'Tapuirama', 11);
INSERT INTO city(id,name,id_state) VALUES(3781, 'Taquaracu de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3782, 'Taruacu', 11);
INSERT INTO city(id,name,id_state) VALUES(3783, 'Tarumirim', 11);
INSERT INTO city(id,name,id_state) VALUES(3784, 'Tebas', 11);
INSERT INTO city(id,name,id_state) VALUES(3785, 'Teixeiras', 11);
INSERT INTO city(id,name,id_state) VALUES(3786, 'Tejuco', 11);
INSERT INTO city(id,name,id_state) VALUES(3787, 'Teofilo Otoni', 11);
INSERT INTO city(id,name,id_state) VALUES(3788, 'Terra Branca', 11);
INSERT INTO city(id,name,id_state) VALUES(3789, 'Timoteo', 11);
INSERT INTO city(id,name,id_state) VALUES(3790, 'Tiradentes', 11);
INSERT INTO city(id,name,id_state) VALUES(3791, 'Tiros', 11);
INSERT INTO city(id,name,id_state) VALUES(3792, 'Tobati', 11);
INSERT INTO city(id,name,id_state) VALUES(3793, 'Tocandira', 11);
INSERT INTO city(id,name,id_state) VALUES(3794, 'Tocantins', 11);
INSERT INTO city(id,name,id_state) VALUES(3795, 'Tocos do Mogi', 11);
INSERT INTO city(id,name,id_state) VALUES(3796, 'Toledo', 11);
INSERT INTO city(id,name,id_state) VALUES(3797, 'Tomas Gonzaga', 11);
INSERT INTO city(id,name,id_state) VALUES(3798, 'Tombos', 11);
INSERT INTO city(id,name,id_state) VALUES(3799, 'Topazio', 11);
INSERT INTO city(id,name,id_state) VALUES(3800, 'Torneiros', 11);
INSERT INTO city(id,name,id_state) VALUES(3801, 'Torreoes', 11);
INSERT INTO city(id,name,id_state) VALUES(3802, 'Tres Coracoes', 11);
INSERT INTO city(id,name,id_state) VALUES(3803, 'Tres Ilhas', 11);
INSERT INTO city(id,name,id_state) VALUES(3804, 'Tres Marias', 11);
INSERT INTO city(id,name,id_state) VALUES(3805, 'Tres Pontas', 11);
INSERT INTO city(id,name,id_state) VALUES(3806, 'Trimonte', 11);
INSERT INTO city(id,name,id_state) VALUES(3807, 'Tuiutinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3808, 'Tumiritinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3809, 'Tupaciguara', 11);
INSERT INTO city(id,name,id_state) VALUES(3810, 'Tuparece', 11);
INSERT INTO city(id,name,id_state) VALUES(3811, 'Turmalina', 11);
INSERT INTO city(id,name,id_state) VALUES(3812, 'Turvolandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3813, 'Uba', 11);
INSERT INTO city(id,name,id_state) VALUES(3814, 'Ubai', 11);
INSERT INTO city(id,name,id_state) VALUES(3815, 'Ubaporanga', 11);
INSERT INTO city(id,name,id_state) VALUES(3816, 'Ubari', 11);
INSERT INTO city(id,name,id_state) VALUES(3817, 'Uberaba', 11);
INSERT INTO city(id,name,id_state) VALUES(3818, 'Uberlandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3819, 'Umburatiba', 11);
INSERT INTO city(id,name,id_state) VALUES(3820, 'Umbuzeiro', 11);
INSERT INTO city(id,name,id_state) VALUES(3821, 'Unai', 11);
INSERT INTO city(id,name,id_state) VALUES(3822, 'Uniao', 11);
INSERT INTO city(id,name,id_state) VALUES(3823, 'Uruana', 11);
INSERT INTO city(id,name,id_state) VALUES(3824, 'Urucania', 11);
INSERT INTO city(id,name,id_state) VALUES(3825, 'Urucuia', 11);
INSERT INTO city(id,name,id_state) VALUES(3826, 'Usina Monte Alegre', 11);
INSERT INTO city(id,name,id_state) VALUES(3827, 'Vai-Volta', 11);
INSERT INTO city(id,name,id_state) VALUES(3828, 'Valadares', 11);
INSERT INTO city(id,name,id_state) VALUES(3829, 'Valao', 11);
INSERT INTO city(id,name,id_state) VALUES(3830, 'Valo Fundo', 11);
INSERT INTO city(id,name,id_state) VALUES(3831, 'Vargem Alegre', 11);
INSERT INTO city(id,name,id_state) VALUES(3832, 'Vargem Bonita', 11);
INSERT INTO city(id,name,id_state) VALUES(3833, 'Vargem Grande do Rio Pardo', 11);
INSERT INTO city(id,name,id_state) VALUES(3834, 'Vargem Linda', 11);
INSERT INTO city(id,name,id_state) VALUES(3835, 'Varginha', 11);
INSERT INTO city(id,name,id_state) VALUES(3836, 'Varjao', 11);
INSERT INTO city(id,name,id_state) VALUES(3837, 'Varzea da Palma', 11);
INSERT INTO city(id,name,id_state) VALUES(3838, 'Varzelandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3839, 'Vau-Acu', 11);
INSERT INTO city(id,name,id_state) VALUES(3840, 'Vazante', 11);
INSERT INTO city(id,name,id_state) VALUES(3841, 'Venda Nova', 11);
INSERT INTO city(id,name,id_state) VALUES(3842, 'Vera Cruz de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3843, 'Verdelandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3844, 'Vereda do Paraiso', 11);
INSERT INTO city(id,name,id_state) VALUES(3845, 'Veredas', 11);
INSERT INTO city(id,name,id_state) VALUES(3846, 'Veredinha', 11);
INSERT INTO city(id,name,id_state) VALUES(3847, 'Verissimo', 11);
INSERT INTO city(id,name,id_state) VALUES(3848, 'Vermelho', 11);
INSERT INTO city(id,name,id_state) VALUES(3849, 'Vermelho Novo', 11);
INSERT INTO city(id,name,id_state) VALUES(3850, 'Vermelho Velho', 11);
INSERT INTO city(id,name,id_state) VALUES(3851, 'Vespasiano', 11);
INSERT INTO city(id,name,id_state) VALUES(3852, 'Vicosa', 11);
INSERT INTO city(id,name,id_state) VALUES(3853, 'Vieiras', 11);
INSERT INTO city(id,name,id_state) VALUES(3854, 'Vila Bom Jesus', 11);
INSERT INTO city(id,name,id_state) VALUES(3855, 'Vila Costina', 11);
INSERT INTO city(id,name,id_state) VALUES(3856, 'Vila Dom Bosco', 11);
INSERT INTO city(id,name,id_state) VALUES(3857, 'Vila dos Anjos', 11);
INSERT INTO city(id,name,id_state) VALUES(3858, 'Vila Natalandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3859, 'Vila Nova de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3860, 'Vila Nova dos Pocoes', 11);
INSERT INTO city(id,name,id_state) VALUES(3861, 'Vila Pereira', 11);
INSERT INTO city(id,name,id_state) VALUES(3862, 'Vilas Boas', 11);
INSERT INTO city(id,name,id_state) VALUES(3863, 'Virgem da Lapa', 11);
INSERT INTO city(id,name,id_state) VALUES(3864, 'Virginia', 11);
INSERT INTO city(id,name,id_state) VALUES(3865, 'Virginopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3866, 'Virgolandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3867, 'Visconde do Rio Branco', 11);
INSERT INTO city(id,name,id_state) VALUES(3868, 'Vista Alegre', 11);
INSERT INTO city(id,name,id_state) VALUES(3869, 'Vitorinos', 11);
INSERT INTO city(id,name,id_state) VALUES(3870, 'Volta Grande', 11);
INSERT INTO city(id,name,id_state) VALUES(3871, 'Wenceslau Braz', 11);
INSERT INTO city(id,name,id_state) VALUES(3872, 'Zelandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3873, 'Zito Soares', 11);
