INSERT INTO state(id,name,initials,id_parents) VALUES(11, 'Minas Gerais', 'MG',1);

INSERT INTO city(id,name,id_state) VALUES(2423, 'Abadia dos Dourados', 11);
INSERT INTO city(id,name,id_state) VALUES(2424, 'Abaete', 11);
INSERT INTO city(id,name,id_state) VALUES(2425, 'Abaete dos Mendes', 11);
INSERT INTO city(id,name,id_state) VALUES(2426, 'Abaiba', 11);
INSERT INTO city(id,name,id_state) VALUES(2427, 'Abre Campo', 11);
INSERT INTO city(id,name,id_state) VALUES(2428, 'Abreus', 11);
INSERT INTO city(id,name,id_state) VALUES(2429, 'Acaiaca', 11);
INSERT INTO city(id,name,id_state) VALUES(2430, 'Acucena', 11);
INSERT INTO city(id,name,id_state) VALUES(2431, 'Acurui', 11);
INSERT INTO city(id,name,id_state) VALUES(2432, 'Adao Colares', 11);
INSERT INTO city(id,name,id_state) VALUES(2433, 'Agua Boa', 11);
INSERT INTO city(id,name,id_state) VALUES(2434, 'Agua Branca de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2435, 'Agua Comprida', 11);
INSERT INTO city(id,name,id_state) VALUES(2436, 'Agua Viva', 11);
INSERT INTO city(id,name,id_state) VALUES(2437, 'Aguanil', 11);
INSERT INTO city(id,name,id_state) VALUES(2438, 'Aguas de Araxa', 11);
INSERT INTO city(id,name,id_state) VALUES(2439, 'Aguas de Contendas', 11);
INSERT INTO city(id,name,id_state) VALUES(2440, 'Aguas Ferreas', 11);
INSERT INTO city(id,name,id_state) VALUES(2441, 'Aguas Formosas', 11);
INSERT INTO city(id,name,id_state) VALUES(2442, 'Aguas Vermelhas', 11);
INSERT INTO city(id,name,id_state) VALUES(2443, 'Aimores', 11);
INSERT INTO city(id,name,id_state) VALUES(2444, 'Aiuruoca', 11);
INSERT INTO city(id,name,id_state) VALUES(2445, 'Alagoa', 11);
INSERT INTO city(id,name,id_state) VALUES(2446, 'Albertina', 11);
INSERT INTO city(id,name,id_state) VALUES(2447, 'Alberto Isaacson', 11);
INSERT INTO city(id,name,id_state) VALUES(2448, 'Albertos', 11);
INSERT INTO city(id,name,id_state) VALUES(2449, 'Aldeia', 11);
INSERT INTO city(id,name,id_state) VALUES(2450, 'Alegre', 11);
INSERT INTO city(id,name,id_state) VALUES(2451, 'Alegria', 11);
INSERT INTO city(id,name,id_state) VALUES(2452, 'Alem Paraiba', 11);
INSERT INTO city(id,name,id_state) VALUES(2453, 'Alexandrita', 11);
INSERT INTO city(id,name,id_state) VALUES(2454, 'Alfenas', 11);
INSERT INTO city(id,name,id_state) VALUES(2455, 'Alfredo Vasconcelos', 11);
INSERT INTO city(id,name,id_state) VALUES(2456, 'Almeida', 11);
INSERT INTO city(id,name,id_state) VALUES(2457, 'Almenara', 11);
INSERT INTO city(id,name,id_state) VALUES(2458, 'Alpercata', 11);
INSERT INTO city(id,name,id_state) VALUES(2459, 'Alpinopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2460, 'Alterosa', 11);
INSERT INTO city(id,name,id_state) VALUES(2461, 'Alto Caparao', 11);
INSERT INTO city(id,name,id_state) VALUES(2462, 'Alto Capim', 11);
INSERT INTO city(id,name,id_state) VALUES(2463, 'Alto de Santa Helena', 11);
INSERT INTO city(id,name,id_state) VALUES(2464, 'Alto Jequitiba', 11);
INSERT INTO city(id,name,id_state) VALUES(2465, 'Alto Maranhao', 11);
INSERT INTO city(id,name,id_state) VALUES(2466, 'Alto Rio Doce', 11);
INSERT INTO city(id,name,id_state) VALUES(2467, 'Altolandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2468, 'Alvacao', 11);
INSERT INTO city(id,name,id_state) VALUES(2469, 'Alvarenga', 11);
INSERT INTO city(id,name,id_state) VALUES(2470, 'Alvinopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2471, 'Alvorada', 11);
INSERT INTO city(id,name,id_state) VALUES(2472, 'Alvorada de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2473, 'Amanda', 11);
INSERT INTO city(id,name,id_state) VALUES(2474, 'Amanhece', 11);
INSERT INTO city(id,name,id_state) VALUES(2475, 'Amarantina', 11);
INSERT INTO city(id,name,id_state) VALUES(2476, 'Amparo da Serra', 11);
INSERT INTO city(id,name,id_state) VALUES(2477, 'Andiroba', 11);
INSERT INTO city(id,name,id_state) VALUES(2478, 'Andradas', 11);
INSERT INTO city(id,name,id_state) VALUES(2479, 'Andrelandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2480, 'Andrequice', 11);
INSERT INTO city(id,name,id_state) VALUES(2481, 'Angaturama', 11);
INSERT INTO city(id,name,id_state) VALUES(2482, 'Angicos de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2483, 'Anguereta', 11);
INSERT INTO city(id,name,id_state) VALUES(2484, 'Angustura', 11);
INSERT INTO city(id,name,id_state) VALUES(2485, 'Antonio Carlos', 11);
INSERT INTO city(id,name,id_state) VALUES(2486, 'Antonio Dias', 11);
INSERT INTO city(id,name,id_state) VALUES(2487, 'Antonio dos Santos', 11);
INSERT INTO city(id,name,id_state) VALUES(2488, 'Antonio Ferreira', 11);
INSERT INTO city(id,name,id_state) VALUES(2489, 'Antonio Pereira', 11);
INSERT INTO city(id,name,id_state) VALUES(2490, 'Antonio Prado de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2491, 'Antunes', 11);
INSERT INTO city(id,name,id_state) VALUES(2492, 'Aparecida de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2493, 'Aracai', 11);
INSERT INTO city(id,name,id_state) VALUES(2494, 'Aracati de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2495, 'Aracitaba', 11);
INSERT INTO city(id,name,id_state) VALUES(2496, 'Aracuai', 11);
INSERT INTO city(id,name,id_state) VALUES(2497, 'Araguari', 11);
INSERT INTO city(id,name,id_state) VALUES(2498, 'Aramirim', 11);
INSERT INTO city(id,name,id_state) VALUES(2499, 'Aranha', 11);
INSERT INTO city(id,name,id_state) VALUES(2500, 'Arantina', 11);
INSERT INTO city(id,name,id_state) VALUES(2501, 'Araponga', 11);
INSERT INTO city(id,name,id_state) VALUES(2502, 'Arapora', 11);
INSERT INTO city(id,name,id_state) VALUES(2503, 'Arapua', 11);
INSERT INTO city(id,name,id_state) VALUES(2504, 'Araujos', 11);
INSERT INTO city(id,name,id_state) VALUES(2505, 'Arauna', 11);
INSERT INTO city(id,name,id_state) VALUES(2506, 'Araxa', 11);
INSERT INTO city(id,name,id_state) VALUES(2507, 'Arcangelo', 11);
INSERT INTO city(id,name,id_state) VALUES(2508, 'Arceburgo', 11);
INSERT INTO city(id,name,id_state) VALUES(2509, 'Arcos', 11);
INSERT INTO city(id,name,id_state) VALUES(2510, 'Areado', 11);
INSERT INTO city(id,name,id_state) VALUES(2511, 'Argenita', 11);
INSERT INTO city(id,name,id_state) VALUES(2512, 'Argirita', 11);
INSERT INTO city(id,name,id_state) VALUES(2513, 'Aricanduva', 11);
INSERT INTO city(id,name,id_state) VALUES(2514, 'Arinos', 11);
INSERT INTO city(id,name,id_state) VALUES(2515, 'Aristides Batista', 11);
INSERT INTO city(id,name,id_state) VALUES(2516, 'Ascencao', 11);
INSERT INTO city(id,name,id_state) VALUES(2517, 'Assarai', 11);
INSERT INTO city(id,name,id_state) VALUES(2518, 'Astolfo Dutra', 11);
INSERT INTO city(id,name,id_state) VALUES(2519, 'Ataleia', 11);
INSERT INTO city(id,name,id_state) VALUES(2520, 'Augusto de Lima', 11);
INSERT INTO city(id,name,id_state) VALUES(2521, 'Avai do Jacinto', 11);
INSERT INTO city(id,name,id_state) VALUES(2522, 'Azurita', 11);
INSERT INTO city(id,name,id_state) VALUES(2523, 'Babilonia', 11);
INSERT INTO city(id,name,id_state) VALUES(2524, 'Bacao', 11);
INSERT INTO city(id,name,id_state) VALUES(2525, 'Baependi', 11);
INSERT INTO city(id,name,id_state) VALUES(2526, 'Baguari', 11);
INSERT INTO city(id,name,id_state) VALUES(2527, 'Baioes', 11);
INSERT INTO city(id,name,id_state) VALUES(2528, 'Balbinopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2529, 'Baldim', 11);
INSERT INTO city(id,name,id_state) VALUES(2530, 'Bambui', 11);
INSERT INTO city(id,name,id_state) VALUES(2531, 'Bandeira', 11);
INSERT INTO city(id,name,id_state) VALUES(2532, 'Bandeira do Sul', 11);
INSERT INTO city(id,name,id_state) VALUES(2533, 'Bandeirantes', 11);
INSERT INTO city(id,name,id_state) VALUES(2534, 'Barao de Cocais', 11);
INSERT INTO city(id,name,id_state) VALUES(2535, 'Barao de Monte Alto', 11);
INSERT INTO city(id,name,id_state) VALUES(2536, 'Barbacena', 11);
INSERT INTO city(id,name,id_state) VALUES(2537, 'Barra Alegre', 11);
INSERT INTO city(id,name,id_state) VALUES(2538, 'Barra da Figueira', 11);
INSERT INTO city(id,name,id_state) VALUES(2539, 'Barra do Ariranha', 11);
INSERT INTO city(id,name,id_state) VALUES(2540, 'Barra do Cuiete', 11);
INSERT INTO city(id,name,id_state) VALUES(2541, 'Barra Feliz', 11);
INSERT INTO city(id,name,id_state) VALUES(2542, 'Barra Longa', 11);
INSERT INTO city(id,name,id_state) VALUES(2543, 'Barranco Alto', 11);
INSERT INTO city(id,name,id_state) VALUES(2544, 'Barreiro da Raiz', 11);
INSERT INTO city(id,name,id_state) VALUES(2545, 'Barreiro do Rio Verde', 11);
INSERT INTO city(id,name,id_state) VALUES(2546, 'Barretos de Alvinopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2547, 'Barrocao', 11);
INSERT INTO city(id,name,id_state) VALUES(2548, 'Barroso', 11);
INSERT INTO city(id,name,id_state) VALUES(2549, 'Bau', 11);
INSERT INTO city(id,name,id_state) VALUES(2550, 'Bela Vista de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2551, 'Belisario', 11);
INSERT INTO city(id,name,id_state) VALUES(2552, 'Belmiro Braga', 11);
INSERT INTO city(id,name,id_state) VALUES(2553, 'Belo Horizonte', 11);
INSERT INTO city(id,name,id_state) VALUES(2554, 'Belo Oriente', 11);
INSERT INTO city(id,name,id_state) VALUES(2555, 'Belo Vale', 11);
INSERT INTO city(id,name,id_state) VALUES(2556, 'Bentopolis de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2557, 'Berilo', 11);
INSERT INTO city(id,name,id_state) VALUES(2558, 'Berizal', 11);
INSERT INTO city(id,name,id_state) VALUES(2559, 'Bertopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2560, 'Betim', 11);
INSERT INTO city(id,name,id_state) VALUES(2561, 'Bias Fortes', 11);
INSERT INTO city(id,name,id_state) VALUES(2562, 'Bicas', 11);
INSERT INTO city(id,name,id_state) VALUES(2563, 'Bicuiba', 11);
INSERT INTO city(id,name,id_state) VALUES(2564, 'Biquinhas', 11);
INSERT INTO city(id,name,id_state) VALUES(2565, 'Bituri', 11);
INSERT INTO city(id,name,id_state) VALUES(2566, 'Boa Esperanca', 11);
INSERT INTO city(id,name,id_state) VALUES(2567, 'Boa Familia', 11);
INSERT INTO city(id,name,id_state) VALUES(2568, 'Boa Uniao de Itabirinha', 11);
INSERT INTO city(id,name,id_state) VALUES(2569, 'Boa Vista de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2570, 'Bocaina de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2571, 'Bocaiuva', 11);
INSERT INTO city(id,name,id_state) VALUES(2572, 'Bom Despacho', 11);
INSERT INTO city(id,name,id_state) VALUES(2573, 'Bom Jardim de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2574, 'Bom Jesus da Cachoeira', 11);
INSERT INTO city(id,name,id_state) VALUES(2575, 'Bom Jesus da Penha', 11);
INSERT INTO city(id,name,id_state) VALUES(2576, 'Bom Jesus do Amparo', 11);
INSERT INTO city(id,name,id_state) VALUES(2577, 'Bom Jesus do Divino', 11);
INSERT INTO city(id,name,id_state) VALUES(2578, 'Bom Jesus do Galho', 11);
INSERT INTO city(id,name,id_state) VALUES(2579, 'Bom Jesus do Madeira', 11);
INSERT INTO city(id,name,id_state) VALUES(2580, 'Bom Pastor', 11);
INSERT INTO city(id,name,id_state) VALUES(2581, 'Bom Repouso', 11);
INSERT INTO city(id,name,id_state) VALUES(2582, 'Bom Retiro', 11);
INSERT INTO city(id,name,id_state) VALUES(2583, 'Bom Sucesso', 11);
INSERT INTO city(id,name,id_state) VALUES(2584, 'Bom Sucesso de Patos', 11);
INSERT INTO city(id,name,id_state) VALUES(2585, 'Bonanca', 11);
INSERT INTO city(id,name,id_state) VALUES(2586, 'Bonfim', 11);
INSERT INTO city(id,name,id_state) VALUES(2587, 'Bonfinopolis de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2588, 'Bonito', 11);
INSERT INTO city(id,name,id_state) VALUES(2589, 'Borba Gato', 11);
INSERT INTO city(id,name,id_state) VALUES(2590, 'Borda da Mata', 11);
INSERT INTO city(id,name,id_state) VALUES(2591, 'Botelhos', 11);
INSERT INTO city(id,name,id_state) VALUES(2592, 'Botumirim', 11);
INSERT INTO city(id,name,id_state) VALUES(2593, 'Bras Pires', 11);
INSERT INTO city(id,name,id_state) VALUES(2594, 'Brasilandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2595, 'Brasilia de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2596, 'Brasopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2597, 'Braunas', 11);
INSERT INTO city(id,name,id_state) VALUES(2598, 'Brejauba', 11);
INSERT INTO city(id,name,id_state) VALUES(2599, 'Brejaubinha', 11);
INSERT INTO city(id,name,id_state) VALUES(2600, 'Brejo Bonito', 11);
INSERT INTO city(id,name,id_state) VALUES(2601, 'Brejo do Amparo', 11);
INSERT INTO city(id,name,id_state) VALUES(2602, 'Brumadinho', 11);
INSERT INTO city(id,name,id_state) VALUES(2603, 'Brumal', 11);
INSERT INTO city(id,name,id_state) VALUES(2604, 'Buarque de Macedo', 11);
INSERT INTO city(id,name,id_state) VALUES(2605, 'Bueno', 11);
INSERT INTO city(id,name,id_state) VALUES(2606, 'Bueno Brandao', 11);
INSERT INTO city(id,name,id_state) VALUES(2607, 'Buenopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2608, 'Bugre', 11);
INSERT INTO city(id,name,id_state) VALUES(2609, 'Buritis', 11);
INSERT INTO city(id,name,id_state) VALUES(2610, 'Buritizeiro', 11);
INSERT INTO city(id,name,id_state) VALUES(2611, 'Caatinga', 11);
INSERT INTO city(id,name,id_state) VALUES(2612, 'Cabeceira Grande', 11);
INSERT INTO city(id,name,id_state) VALUES(2613, 'Cabo Verde', 11);
INSERT INTO city(id,name,id_state) VALUES(2614, 'Caburu', 11);
INSERT INTO city(id,name,id_state) VALUES(2615, 'Cacaratiba', 11);
INSERT INTO city(id,name,id_state) VALUES(2616, 'Cacarema', 11);
INSERT INTO city(id,name,id_state) VALUES(2617, 'Cachoeira Alegre', 11);
INSERT INTO city(id,name,id_state) VALUES(2618, 'Cachoeira da Prata', 11);
INSERT INTO city(id,name,id_state) VALUES(2619, 'Cachoeira de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2620, 'Cachoeira de Pajeu', 11);
INSERT INTO city(id,name,id_state) VALUES(2621, 'Cachoeira de Santa Cruz', 11);
INSERT INTO city(id,name,id_state) VALUES(2622, 'Cachoeira do Brumado', 11);
INSERT INTO city(id,name,id_state) VALUES(2623, 'Cachoeira do Campo', 11);
INSERT INTO city(id,name,id_state) VALUES(2624, 'Cachoeira do Manteiga', 11);
INSERT INTO city(id,name,id_state) VALUES(2625, 'Cachoeira do Vale', 11);
INSERT INTO city(id,name,id_state) VALUES(2626, 'Cachoeira dos Antunes', 11);
INSERT INTO city(id,name,id_state) VALUES(2627, 'Cachoeira Dourada', 11);
INSERT INTO city(id,name,id_state) VALUES(2628, 'Cachoeirinha', 11);
INSERT INTO city(id,name,id_state) VALUES(2629, 'Caetano Lopes', 11);
INSERT INTO city(id,name,id_state) VALUES(2630, 'Caetanopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2631, 'Caete', 11);
INSERT INTO city(id,name,id_state) VALUES(2632, 'Caiana', 11);
INSERT INTO city(id,name,id_state) VALUES(2633, 'Caiapo', 11);
INSERT INTO city(id,name,id_state) VALUES(2634, 'Cajuri', 11);
INSERT INTO city(id,name,id_state) VALUES(2635, 'Caldas', 11);
INSERT INTO city(id,name,id_state) VALUES(2636, 'Calixto', 11);
INSERT INTO city(id,name,id_state) VALUES(2637, 'Camacho', 11);
INSERT INTO city(id,name,id_state) VALUES(2638, 'Camanducaia', 11);
INSERT INTO city(id,name,id_state) VALUES(2639, 'Camargos', 11);
INSERT INTO city(id,name,id_state) VALUES(2640, 'Cambui', 11);
INSERT INTO city(id,name,id_state) VALUES(2641, 'Cambuquira', 11);
INSERT INTO city(id,name,id_state) VALUES(2642, 'Campanario', 11);
INSERT INTO city(id,name,id_state) VALUES(2643, 'Campanha', 11);
INSERT INTO city(id,name,id_state) VALUES(2644, 'Campestre', 11);
INSERT INTO city(id,name,id_state) VALUES(2645, 'Campestrinho', 11);
INSERT INTO city(id,name,id_state) VALUES(2646, 'Campina Verde', 11);
INSERT INTO city(id,name,id_state) VALUES(2647, 'Campo Alegre de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2648, 'Campo Azul', 11);
INSERT INTO city(id,name,id_state) VALUES(2649, 'Campo Belo', 11);
INSERT INTO city(id,name,id_state) VALUES(2650, 'Campo do Meio', 11);
INSERT INTO city(id,name,id_state) VALUES(2651, 'Campo Florido', 11);
INSERT INTO city(id,name,id_state) VALUES(2652, 'Campo Redondo', 11);
INSERT INTO city(id,name,id_state) VALUES(2653, 'Campolide', 11);
INSERT INTO city(id,name,id_state) VALUES(2654, 'Campos Altos', 11);
INSERT INTO city(id,name,id_state) VALUES(2655, 'Campos Gerais', 11);
INSERT INTO city(id,name,id_state) VALUES(2656, 'Cana Verde', 11);
INSERT INTO city(id,name,id_state) VALUES(2657, 'Canaa', 11);
INSERT INTO city(id,name,id_state) VALUES(2658, 'Canabrava', 11);
INSERT INTO city(id,name,id_state) VALUES(2659, 'Canapolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2660, 'Canastrao', 11);
INSERT INTO city(id,name,id_state) VALUES(2661, 'Candeias', 11);
INSERT INTO city(id,name,id_state) VALUES(2662, 'Canoeiros', 11);
INSERT INTO city(id,name,id_state) VALUES(2663, 'Cantagalo', 11);
INSERT INTO city(id,name,id_state) VALUES(2664, 'Caparao', 11);
INSERT INTO city(id,name,id_state) VALUES(2665, 'Capela Nova', 11);
INSERT INTO city(id,name,id_state) VALUES(2666, 'Capelinha', 11);
INSERT INTO city(id,name,id_state) VALUES(2667, 'Capetinga', 11);
INSERT INTO city(id,name,id_state) VALUES(2668, 'Capim Branco', 11);
INSERT INTO city(id,name,id_state) VALUES(2669, 'Capinopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2670, 'Capitania', 11);
INSERT INTO city(id,name,id_state) VALUES(2671, 'Capitao Andrade', 11);
INSERT INTO city(id,name,id_state) VALUES(2672, 'Capitao Eneas', 11);
INSERT INTO city(id,name,id_state) VALUES(2673, 'Capitolio', 11);
INSERT INTO city(id,name,id_state) VALUES(2674, 'Caputira', 11);
INSERT INTO city(id,name,id_state) VALUES(2675, 'Carai', 11);
INSERT INTO city(id,name,id_state) VALUES(2676, 'Caranaiba', 11);
INSERT INTO city(id,name,id_state) VALUES(2677, 'Carandai', 11);
INSERT INTO city(id,name,id_state) VALUES(2678, 'Carangola', 11);
INSERT INTO city(id,name,id_state) VALUES(2679, 'Caratinga', 11);
INSERT INTO city(id,name,id_state) VALUES(2680, 'Carbonita', 11);
INSERT INTO city(id,name,id_state) VALUES(2681, 'Cardeal Mota', 11);
INSERT INTO city(id,name,id_state) VALUES(2682, 'Careacu', 11);
INSERT INTO city(id,name,id_state) VALUES(2683, 'Carioca', 11);
INSERT INTO city(id,name,id_state) VALUES(2684, 'Carlos Alves', 11);
INSERT INTO city(id,name,id_state) VALUES(2685, 'Carlos Chagas', 11);
INSERT INTO city(id,name,id_state) VALUES(2686, 'Carmesia', 11);
INSERT INTO city(id,name,id_state) VALUES(2687, 'Carmo da Cachoeira', 11);
INSERT INTO city(id,name,id_state) VALUES(2688, 'Carmo da Mata', 11);
INSERT INTO city(id,name,id_state) VALUES(2689, 'Carmo de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2690, 'Carmo do Cajuru', 11);
INSERT INTO city(id,name,id_state) VALUES(2691, 'Carmo do Paranaiba', 11);
INSERT INTO city(id,name,id_state) VALUES(2692, 'Carmo do Rio Claro', 11);
INSERT INTO city(id,name,id_state) VALUES(2693, 'Carmopolis de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2694, 'Carneirinho', 11);
INSERT INTO city(id,name,id_state) VALUES(2695, 'Carrancas', 11);
INSERT INTO city(id,name,id_state) VALUES(2696, 'Carvalho de Brito', 11);
INSERT INTO city(id,name,id_state) VALUES(2697, 'Carvalhopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2698, 'Carvalhos', 11);
INSERT INTO city(id,name,id_state) VALUES(2699, 'Casa Grande', 11);
INSERT INTO city(id,name,id_state) VALUES(2700, 'Cascalho Rico', 11);
INSERT INTO city(id,name,id_state) VALUES(2701, 'Cassia', 11);
INSERT INTO city(id,name,id_state) VALUES(2702, 'Cataguarino', 11);
INSERT INTO city(id,name,id_state) VALUES(2703, 'Cataguases', 11);
INSERT INTO city(id,name,id_state) VALUES(2704, 'Catajas', 11);
INSERT INTO city(id,name,id_state) VALUES(2705, 'Catas Altas', 11);
INSERT INTO city(id,name,id_state) VALUES(2706, 'Catas Altas da Noruega', 11);
INSERT INTO city(id,name,id_state) VALUES(2707, 'Catiara', 11);
INSERT INTO city(id,name,id_state) VALUES(2708, 'Catuji', 11);
INSERT INTO city(id,name,id_state) VALUES(2709, 'Catune', 11);
INSERT INTO city(id,name,id_state) VALUES(2710, 'Catuni', 11);
INSERT INTO city(id,name,id_state) VALUES(2711, 'Caxambu', 11);
INSERT INTO city(id,name,id_state) VALUES(2712, 'Cedro do Abaete', 11);
INSERT INTO city(id,name,id_state) VALUES(2713, 'Centenario', 11);
INSERT INTO city(id,name,id_state) VALUES(2714, 'Central de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2715, 'Central de Santa Helena', 11);
INSERT INTO city(id,name,id_state) VALUES(2716, 'Centralina', 11);
INSERT INTO city(id,name,id_state) VALUES(2717, 'Cervo', 11);
INSERT INTO city(id,name,id_state) VALUES(2718, 'Chacara', 11);
INSERT INTO city(id,name,id_state) VALUES(2719, 'Chale', 11);
INSERT INTO city(id,name,id_state) VALUES(2720, 'Chapada de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2721, 'Chapada do Norte', 11);
INSERT INTO city(id,name,id_state) VALUES(2722, 'Chaveslandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2723, 'Chiador', 11);
INSERT INTO city(id,name,id_state) VALUES(2724, 'Chonim', 11);
INSERT INTO city(id,name,id_state) VALUES(2725, 'Chumbo', 11);
INSERT INTO city(id,name,id_state) VALUES(2726, 'Cipotanea', 11);
INSERT INTO city(id,name,id_state) VALUES(2727, 'Cisneiros', 11);
INSERT INTO city(id,name,id_state) VALUES(2728, 'Citrolandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2729, 'Claraval', 11);
INSERT INTO city(id,name,id_state) VALUES(2730, 'Claro de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2731, 'Claro dos Pocoes', 11);
INSERT INTO city(id,name,id_state) VALUES(2732, 'Claudio', 11);
INSERT INTO city(id,name,id_state) VALUES(2733, 'Claudio Manuel', 11);
INSERT INTO city(id,name,id_state) VALUES(2734, 'Cocais', 11);
INSERT INTO city(id,name,id_state) VALUES(2735, 'Coco', 11);
INSERT INTO city(id,name,id_state) VALUES(2736, 'Coimbra', 11);
INSERT INTO city(id,name,id_state) VALUES(2737, 'Coluna', 11);
INSERT INTO city(id,name,id_state) VALUES(2738, 'Comendador Gomes', 11);
INSERT INTO city(id,name,id_state) VALUES(2739, 'Comercinho', 11);
INSERT INTO city(id,name,id_state) VALUES(2740, 'Conceicao da Aparecida', 11);
INSERT INTO city(id,name,id_state) VALUES(2741, 'Conceicao da Barra de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2742, 'Conceicao da Boa Vista', 11);
INSERT INTO city(id,name,id_state) VALUES(2743, 'Conceicao da Brejauba', 11);
INSERT INTO city(id,name,id_state) VALUES(2744, 'Conceicao da Ibitipoca', 11);
INSERT INTO city(id,name,id_state) VALUES(2745, 'Conceicao das Alagoas', 11);
INSERT INTO city(id,name,id_state) VALUES(2746, 'Conceicao das Pedras', 11);
INSERT INTO city(id,name,id_state) VALUES(2747, 'Conceicao de Ipanema', 11);
INSERT INTO city(id,name,id_state) VALUES(2748, 'Conceicao de Itagua', 11);
INSERT INTO city(id,name,id_state) VALUES(2749, 'Conceicao de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2750, 'Conceicao de Piracicaba', 11);
INSERT INTO city(id,name,id_state) VALUES(2751, 'Conceicao de Tronqueiras', 11);
INSERT INTO city(id,name,id_state) VALUES(2752, 'Conceicao do Capim', 11);
INSERT INTO city(id,name,id_state) VALUES(2753, 'Conceicao do Formoso', 11);
INSERT INTO city(id,name,id_state) VALUES(2754, 'Conceicao do Mato Dentro', 11);
INSERT INTO city(id,name,id_state) VALUES(2755, 'Conceicao do Para', 11);
INSERT INTO city(id,name,id_state) VALUES(2756, 'Conceicao do Rio Acima', 11);
INSERT INTO city(id,name,id_state) VALUES(2757, 'Conceicao do Rio Verde', 11);
INSERT INTO city(id,name,id_state) VALUES(2758, 'Conceicao dos Ouros', 11);
INSERT INTO city(id,name,id_state) VALUES(2759, 'Concordia de Mucuri', 11);
INSERT INTO city(id,name,id_state) VALUES(2760, 'Condado do Norte', 11);
INSERT INTO city(id,name,id_state) VALUES(2761, 'Conego Joao Pio', 11);
INSERT INTO city(id,name,id_state) VALUES(2762, 'Conego Marinho', 11);
INSERT INTO city(id,name,id_state) VALUES(2763, 'Confins', 11);
INSERT INTO city(id,name,id_state) VALUES(2764, 'Congonhal', 11);
INSERT INTO city(id,name,id_state) VALUES(2765, 'Congonhas', 11);
INSERT INTO city(id,name,id_state) VALUES(2766, 'Congonhas do Norte', 11);
INSERT INTO city(id,name,id_state) VALUES(2767, 'Conquista', 11);
INSERT INTO city(id,name,id_state) VALUES(2768, 'Conselheiro Lafaiete', 11);
INSERT INTO city(id,name,id_state) VALUES(2769, 'Conselheiro Mata', 11);
INSERT INTO city(id,name,id_state) VALUES(2770, 'Conselheiro Pena', 11);
INSERT INTO city(id,name,id_state) VALUES(2771, 'Consolacao', 11);
INSERT INTO city(id,name,id_state) VALUES(2772, 'Contagem', 11);
INSERT INTO city(id,name,id_state) VALUES(2773, 'Contrato', 11);
INSERT INTO city(id,name,id_state) VALUES(2774, 'Contria', 11);
INSERT INTO city(id,name,id_state) VALUES(2775, 'Coqueiral', 11);
INSERT INTO city(id,name,id_state) VALUES(2776, 'Coracao de Jesus', 11);
INSERT INTO city(id,name,id_state) VALUES(2777, 'Cordisburgo', 11);
INSERT INTO city(id,name,id_state) VALUES(2778, 'Cordislandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2779, 'Corinto', 11);
INSERT INTO city(id,name,id_state) VALUES(2780, 'Coroaci', 11);
INSERT INTO city(id,name,id_state) VALUES(2781, 'Coromandel', 11);
INSERT INTO city(id,name,id_state) VALUES(2782, 'Coronel Fabriciano', 11);
INSERT INTO city(id,name,id_state) VALUES(2783, 'Coronel Murta', 11);
INSERT INTO city(id,name,id_state) VALUES(2784, 'Coronel Pacheco', 11);
INSERT INTO city(id,name,id_state) VALUES(2785, 'Coronel Xavier Chaves', 11);
INSERT INTO city(id,name,id_state) VALUES(2786, 'Corrego Danta', 11);
INSERT INTO city(id,name,id_state) VALUES(2787, 'Corrego do Barro', 11);
INSERT INTO city(id,name,id_state) VALUES(2788, 'Corrego do Bom Jesus', 11);
INSERT INTO city(id,name,id_state) VALUES(2789, 'Corrego do Ouro', 11);
INSERT INTO city(id,name,id_state) VALUES(2790, 'Corrego Fundo', 11);
INSERT INTO city(id,name,id_state) VALUES(2791, 'Corrego Novo', 11);
INSERT INTO city(id,name,id_state) VALUES(2792, 'Corregos', 11);
INSERT INTO city(id,name,id_state) VALUES(2793, 'Correia de Almeida', 11);
INSERT INTO city(id,name,id_state) VALUES(2794, 'Correntinho', 11);
INSERT INTO city(id,name,id_state) VALUES(2795, 'Costa Sena', 11);
INSERT INTO city(id,name,id_state) VALUES(2796, 'Costas', 11);
INSERT INTO city(id,name,id_state) VALUES(2797, 'Couto de Magalhaes de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2798, 'Crisolia', 11);
INSERT INTO city(id,name,id_state) VALUES(2799, 'Crisolita', 11);
INSERT INTO city(id,name,id_state) VALUES(2800, 'Crispim Jaques', 11);
INSERT INTO city(id,name,id_state) VALUES(2801, 'Cristais', 11);
INSERT INTO city(id,name,id_state) VALUES(2802, 'Cristalia', 11);
INSERT INTO city(id,name,id_state) VALUES(2803, 'Cristiano Otoni', 11);
INSERT INTO city(id,name,id_state) VALUES(2804, 'Cristina', 11);
INSERT INTO city(id,name,id_state) VALUES(2805, 'Crucilandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2806, 'Cruzeiro da Fortaleza', 11);
INSERT INTO city(id,name,id_state) VALUES(2807, 'Cruzeiro dos Peixotos', 11);
INSERT INTO city(id,name,id_state) VALUES(2808, 'Cruzilia', 11);
INSERT INTO city(id,name,id_state) VALUES(2809, 'Cubas', 11);
INSERT INTO city(id,name,id_state) VALUES(2810, 'Cuite Velho', 11);
INSERT INTO city(id,name,id_state) VALUES(2811, 'Cuparaque', 11);
INSERT INTO city(id,name,id_state) VALUES(2812, 'Curimatai', 11);
INSERT INTO city(id,name,id_state) VALUES(2813, 'Curral de Dentro', 11);
INSERT INTO city(id,name,id_state) VALUES(2814, 'Curvelo', 11);
INSERT INTO city(id,name,id_state) VALUES(2815, 'Datas', 11);
INSERT INTO city(id,name,id_state) VALUES(2816, 'Delfim Moreira', 11);
INSERT INTO city(id,name,id_state) VALUES(2817, 'Delfinopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2818, 'Delta', 11);
INSERT INTO city(id,name,id_state) VALUES(2819, 'Deputado Augusto Clementino', 11);
INSERT INTO city(id,name,id_state) VALUES(2820, 'Derribadinha', 11);
INSERT INTO city(id,name,id_state) VALUES(2821, 'Descoberto', 11);
INSERT INTO city(id,name,id_state) VALUES(2822, 'Desembargador Otoni', 11);
INSERT INTO city(id,name,id_state) VALUES(2823, 'Desemboque', 11);
INSERT INTO city(id,name,id_state) VALUES(2824, 'Desterro de Entre Rios', 11);
INSERT INTO city(id,name,id_state) VALUES(2825, 'Desterro do Melo', 11);
INSERT INTO city(id,name,id_state) VALUES(2826, 'Diamante de Uba', 11);
INSERT INTO city(id,name,id_state) VALUES(2827, 'Diamantina', 11);
INSERT INTO city(id,name,id_state) VALUES(2828, 'Dias', 11);
INSERT INTO city(id,name,id_state) VALUES(2829, 'Dias Tavares', 11);
INSERT INTO city(id,name,id_state) VALUES(2830, 'Diogo de Vasconcelos', 11);
INSERT INTO city(id,name,id_state) VALUES(2831, 'Dionisio', 11);
INSERT INTO city(id,name,id_state) VALUES(2832, 'Divinesia', 11);
INSERT INTO city(id,name,id_state) VALUES(2833, 'Divino', 11);
INSERT INTO city(id,name,id_state) VALUES(2834, 'Divino das Laranjeiras', 11);
INSERT INTO city(id,name,id_state) VALUES(2835, 'Divino de Virgolandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2836, 'Divino Espirito Santo', 11);
INSERT INTO city(id,name,id_state) VALUES(2837, 'Divinolandia de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2838, 'Divinopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2839, 'Divisa Alegre', 11);
INSERT INTO city(id,name,id_state) VALUES(2840, 'Divisa Nova', 11);
INSERT INTO city(id,name,id_state) VALUES(2841, 'Divisopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2842, 'Dois de Abril', 11);
INSERT INTO city(id,name,id_state) VALUES(2843, 'Dom Cavati', 11);
INSERT INTO city(id,name,id_state) VALUES(2844, 'Dom Joaquim', 11);
INSERT INTO city(id,name,id_state) VALUES(2845, 'Dom Lara', 11);
INSERT INTO city(id,name,id_state) VALUES(2846, 'Dom Modesto', 11);
INSERT INTO city(id,name,id_state) VALUES(2847, 'Dom Silverio', 11);
INSERT INTO city(id,name,id_state) VALUES(2848, 'Dom Vicoso', 11);
INSERT INTO city(id,name,id_state) VALUES(2849, 'Dona Euzebia', 11);
INSERT INTO city(id,name,id_state) VALUES(2850, 'Dores da Vitoria', 11);
INSERT INTO city(id,name,id_state) VALUES(2851, 'Dores de Campos', 11);
INSERT INTO city(id,name,id_state) VALUES(2852, 'Dores de Guanhaes', 11);
INSERT INTO city(id,name,id_state) VALUES(2853, 'Dores do Indaia', 11);
INSERT INTO city(id,name,id_state) VALUES(2854, 'Dores do Paraibuna', 11);
INSERT INTO city(id,name,id_state) VALUES(2855, 'Dores do Turvo', 11);
INSERT INTO city(id,name,id_state) VALUES(2856, 'Doresopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2857, 'Douradinho', 11);
INSERT INTO city(id,name,id_state) VALUES(2858, 'Douradoquara', 11);
INSERT INTO city(id,name,id_state) VALUES(2859, 'Doutor Campolina', 11);
INSERT INTO city(id,name,id_state) VALUES(2860, 'Doutor Lund', 11);
INSERT INTO city(id,name,id_state) VALUES(2861, 'Durande', 11);
INSERT INTO city(id,name,id_state) VALUES(2862, 'Edgard Melo', 11);
INSERT INTO city(id,name,id_state) VALUES(2863, 'Eloi Mendes', 11);
INSERT INTO city(id,name,id_state) VALUES(2864, 'Emboabas', 11);
INSERT INTO city(id,name,id_state) VALUES(2865, 'Engenheiro Caldas', 11);
INSERT INTO city(id,name,id_state) VALUES(2866, 'Engenheiro Correia', 11);
INSERT INTO city(id,name,id_state) VALUES(2867, 'Engenheiro Navarro', 11);
INSERT INTO city(id,name,id_state) VALUES(2868, 'Engenheiro Schnoor', 11);
INSERT INTO city(id,name,id_state) VALUES(2869, 'Engenho do Ribeiro', 11);
INSERT INTO city(id,name,id_state) VALUES(2870, 'Engenho Novo', 11);
INSERT INTO city(id,name,id_state) VALUES(2871, 'Entre Folhas', 11);
INSERT INTO city(id,name,id_state) VALUES(2872, 'Entre Rios de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2873, 'Epaminondas Otoni', 11);
INSERT INTO city(id,name,id_state) VALUES(2874, 'Ermidinha', 11);
INSERT INTO city(id,name,id_state) VALUES(2875, 'Ervalia', 11);
INSERT INTO city(id,name,id_state) VALUES(2876, 'Esmeraldas', 11);
INSERT INTO city(id,name,id_state) VALUES(2877, 'Esmeraldas de Ferros', 11);
INSERT INTO city(id,name,id_state) VALUES(2878, 'Espera Feliz', 11);
INSERT INTO city(id,name,id_state) VALUES(2879, 'Espinosa', 11);
INSERT INTO city(id,name,id_state) VALUES(2880, 'Espirito Santo do Dourado', 11);
INSERT INTO city(id,name,id_state) VALUES(2881, 'Esteios', 11);
INSERT INTO city(id,name,id_state) VALUES(2882, 'Estevao de Araujo', 11);
INSERT INTO city(id,name,id_state) VALUES(2883, 'Estiva', 11);
INSERT INTO city(id,name,id_state) VALUES(2884, 'Estrela da Barra', 11);
INSERT INTO city(id,name,id_state) VALUES(2885, 'Estrela Dalva', 11);
INSERT INTO city(id,name,id_state) VALUES(2886, 'Estrela de Jordania', 11);
INSERT INTO city(id,name,id_state) VALUES(2887, 'Estrela do Indaia', 11);
INSERT INTO city(id,name,id_state) VALUES(2888, 'Estrela do Sul', 11);
INSERT INTO city(id,name,id_state) VALUES(2889, 'Eugenopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2890, 'Euxenita', 11);
INSERT INTO city(id,name,id_state) VALUES(2891, 'Ewbank da Camara', 11);
INSERT INTO city(id,name,id_state) VALUES(2892, 'Expedicionario Alicio', 11);
INSERT INTO city(id,name,id_state) VALUES(2893, 'Extracao', 11);
INSERT INTO city(id,name,id_state) VALUES(2894, 'Extrema', 11);
INSERT INTO city(id,name,id_state) VALUES(2895, 'Fama', 11);
INSERT INTO city(id,name,id_state) VALUES(2896, 'Faria Lemos', 11);
INSERT INTO city(id,name,id_state) VALUES(2897, 'Farias', 11);
INSERT INTO city(id,name,id_state) VALUES(2898, 'Fechados', 11);
INSERT INTO city(id,name,id_state) VALUES(2899, 'Felicina', 11);
INSERT INTO city(id,name,id_state) VALUES(2900, 'Felicio dos Santos', 11);
INSERT INTO city(id,name,id_state) VALUES(2901, 'Felisburgo', 11);
INSERT INTO city(id,name,id_state) VALUES(2902, 'Felixlandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2903, 'Fernandes Tourinho', 11);
INSERT INTO city(id,name,id_state) VALUES(2904, 'Fernao Dias', 11);
INSERT INTO city(id,name,id_state) VALUES(2905, 'Ferreiras', 11);
INSERT INTO city(id,name,id_state) VALUES(2906, 'Ferreiropolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2907, 'Ferros', 11);
INSERT INTO city(id,name,id_state) VALUES(2908, 'Ferruginha', 11);
INSERT INTO city(id,name,id_state) VALUES(2909, 'Fervedouro', 11);
INSERT INTO city(id,name,id_state) VALUES(2910, 'Fidalgo', 11);
INSERT INTO city(id,name,id_state) VALUES(2911, 'Fidelandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2912, 'Flor de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2913, 'Floralia', 11);
INSERT INTO city(id,name,id_state) VALUES(2914, 'Floresta', 11);
INSERT INTO city(id,name,id_state) VALUES(2915, 'Florestal', 11);
INSERT INTO city(id,name,id_state) VALUES(2916, 'Florestina', 11);
INSERT INTO city(id,name,id_state) VALUES(2917, 'Fonseca', 11);
INSERT INTO city(id,name,id_state) VALUES(2918, 'Formiga', 11);
INSERT INTO city(id,name,id_state) VALUES(2919, 'Formoso', 11);
INSERT INTO city(id,name,id_state) VALUES(2920, 'Fortaleza de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2921, 'Fortuna de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(2922, 'Francisco Badaro', 11);
INSERT INTO city(id,name,id_state) VALUES(2923, 'Francisco Dumont', 11);
INSERT INTO city(id,name,id_state) VALUES(2924, 'Francisco Sa', 11);
INSERT INTO city(id,name,id_state) VALUES(2925, 'Franciscopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2926, 'Frei Eustaquio', 11);
INSERT INTO city(id,name,id_state) VALUES(2927, 'Frei Gaspar', 11);
INSERT INTO city(id,name,id_state) VALUES(2928, 'Frei Gonzaga', 11);
INSERT INTO city(id,name,id_state) VALUES(2929, 'Frei Inocencio', 11);
INSERT INTO city(id,name,id_state) VALUES(2930, 'Frei Jorge', 11);
INSERT INTO city(id,name,id_state) VALUES(2931, 'Frei Lagonegro', 11);
INSERT INTO city(id,name,id_state) VALUES(2932, 'Frei Orlando', 11);
INSERT INTO city(id,name,id_state) VALUES(2933, 'Frei Serafim', 11);
INSERT INTO city(id,name,id_state) VALUES(2934, 'Freire Cardoso', 11);
INSERT INTO city(id,name,id_state) VALUES(2935, 'Fronteira', 11);
INSERT INTO city(id,name,id_state) VALUES(2936, 'Fronteira dos Vales', 11);
INSERT INTO city(id,name,id_state) VALUES(2937, 'Frutal', 11);
INSERT INTO city(id,name,id_state) VALUES(2938, 'Funchal', 11);
INSERT INTO city(id,name,id_state) VALUES(2939, 'Funilandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2940, 'Furnas', 11);
INSERT INTO city(id,name,id_state) VALUES(2941, 'Furquim', 11);
INSERT INTO city(id,name,id_state) VALUES(2942, 'Galena', 11);
INSERT INTO city(id,name,id_state) VALUES(2943, 'Galileia', 11);
INSERT INTO city(id,name,id_state) VALUES(2944, 'Gama', 11);
INSERT INTO city(id,name,id_state) VALUES(2945, 'Gameleiras', 11);
INSERT INTO city(id,name,id_state) VALUES(2946, 'Garapuava', 11);
INSERT INTO city(id,name,id_state) VALUES(2947, 'Gaviao', 11);
INSERT INTO city(id,name,id_state) VALUES(2948, 'Genipapo', 11);
INSERT INTO city(id,name,id_state) VALUES(2949, 'Glaucilandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2950, 'Glaura', 11);
INSERT INTO city(id,name,id_state) VALUES(2951, 'Glucinio', 11);
INSERT INTO city(id,name,id_state) VALUES(2952, 'Goiabeira', 11);
INSERT INTO city(id,name,id_state) VALUES(2953, 'Goiana', 11);
INSERT INTO city(id,name,id_state) VALUES(2954, 'Goianases', 11);
INSERT INTO city(id,name,id_state) VALUES(2955, 'Goncalves', 11);
INSERT INTO city(id,name,id_state) VALUES(2956, 'Gonzaga', 11);
INSERT INTO city(id,name,id_state) VALUES(2957, 'Gororos', 11);
INSERT INTO city(id,name,id_state) VALUES(2958, 'Gorutuba', 11);
INSERT INTO city(id,name,id_state) VALUES(2959, 'Gouvea', 11);
INSERT INTO city(id,name,id_state) VALUES(2960, 'Governador Valadares', 11);
INSERT INTO city(id,name,id_state) VALUES(2961, 'Graminea', 11);
INSERT INTO city(id,name,id_state) VALUES(2962, 'Granada', 11);
INSERT INTO city(id,name,id_state) VALUES(2963, 'Grao Mogol', 11);
INSERT INTO city(id,name,id_state) VALUES(2964, 'Grota', 11);
INSERT INTO city(id,name,id_state) VALUES(2965, 'Grupiara', 11);
INSERT INTO city(id,name,id_state) VALUES(2966, 'Guacui', 11);
INSERT INTO city(id,name,id_state) VALUES(2967, 'Guaipava', 11);
INSERT INTO city(id,name,id_state) VALUES(2968, 'Guanhaes', 11);
INSERT INTO city(id,name,id_state) VALUES(2969, 'Guape', 11);
INSERT INTO city(id,name,id_state) VALUES(2970, 'Guaraciaba', 11);
INSERT INTO city(id,name,id_state) VALUES(2971, 'Guaraciama', 11);
INSERT INTO city(id,name,id_state) VALUES(2972, 'Guaranesia', 11);
INSERT INTO city(id,name,id_state) VALUES(2973, 'Guarani', 11);
INSERT INTO city(id,name,id_state) VALUES(2974, 'Guaranilandia', 11);
INSERT INTO city(id,name,id_state) VALUES(2975, 'Guarara', 11);
INSERT INTO city(id,name,id_state) VALUES(2976, 'Guarataia', 11);
INSERT INTO city(id,name,id_state) VALUES(2977, 'Guarda dos Ferreiros', 11);
INSERT INTO city(id,name,id_state) VALUES(2978, 'Guarda-Mor', 11);
INSERT INTO city(id,name,id_state) VALUES(2979, 'Guardinha', 11);
INSERT INTO city(id,name,id_state) VALUES(2980, 'Guaxima', 11);
INSERT INTO city(id,name,id_state) VALUES(2981, 'Guaxupe', 11);
INSERT INTO city(id,name,id_state) VALUES(2982, 'Guidoval', 11);
INSERT INTO city(id,name,id_state) VALUES(2983, 'Guimarania', 11);
INSERT INTO city(id,name,id_state) VALUES(2984, 'Guinda', 11);
INSERT INTO city(id,name,id_state) VALUES(2985, 'Guiricema', 11);
INSERT INTO city(id,name,id_state) VALUES(2986, 'Gurinhata', 11);
INSERT INTO city(id,name,id_state) VALUES(2987, 'Heliodora', 11);
INSERT INTO city(id,name,id_state) VALUES(2988, 'Hematita', 11);
INSERT INTO city(id,name,id_state) VALUES(2989, 'Hermilo Alves', 11);
INSERT INTO city(id,name,id_state) VALUES(2990, 'Honoropolis', 11);
INSERT INTO city(id,name,id_state) VALUES(2991, 'Iapu', 11);
INSERT INTO city(id,name,id_state) VALUES(2992, 'Ibertioga', 11);
INSERT INTO city(id,name,id_state) VALUES(2993, 'Ibia', 11);
INSERT INTO city(id,name,id_state) VALUES(2994, 'Ibiai', 11);
INSERT INTO city(id,name,id_state) VALUES(2995, 'Ibiracatu', 11);
INSERT INTO city(id,name,id_state) VALUES(2996, 'Ibiraci', 11);
INSERT INTO city(id,name,id_state) VALUES(2997, 'Ibirite', 11);
INSERT INTO city(id,name,id_state) VALUES(2998, 'Ibitira', 11);
INSERT INTO city(id,name,id_state) VALUES(2999, 'Ibitiura de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3000, 'Ibituruna', 11);
INSERT INTO city(id,name,id_state) VALUES(3001, 'Icarai de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3002, 'Igarape', 11);
INSERT INTO city(id,name,id_state) VALUES(3003, 'Igaratinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3004, 'Iguatama', 11);
INSERT INTO city(id,name,id_state) VALUES(3005, 'Ijaci', 11);
INSERT INTO city(id,name,id_state) VALUES(3006, 'Ilheus do Prata', 11);
INSERT INTO city(id,name,id_state) VALUES(3007, 'Ilicinea', 11);
INSERT INTO city(id,name,id_state) VALUES(3008, 'Imbe', 11);
INSERT INTO city(id,name,id_state) VALUES(3009, 'Inconfidentes', 11);
INSERT INTO city(id,name,id_state) VALUES(3010, 'Indaiabira', 11);
INSERT INTO city(id,name,id_state) VALUES(3011, 'Independencia', 11);
INSERT INTO city(id,name,id_state) VALUES(3012, 'Indianopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3013, 'Ingai', 11);
INSERT INTO city(id,name,id_state) VALUES(3014, 'Inhai', 11);
INSERT INTO city(id,name,id_state) VALUES(3015, 'Inhapim', 11);
INSERT INTO city(id,name,id_state) VALUES(3016, 'Inhauma', 11);
INSERT INTO city(id,name,id_state) VALUES(3017, 'Inimutaba', 11);
INSERT INTO city(id,name,id_state) VALUES(3018, 'Ipaba', 11);
INSERT INTO city(id,name,id_state) VALUES(3019, 'Ipanema', 11);
INSERT INTO city(id,name,id_state) VALUES(3020, 'Ipatinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3021, 'Ipiacu', 11);
INSERT INTO city(id,name,id_state) VALUES(3022, 'Ipoema', 11);
INSERT INTO city(id,name,id_state) VALUES(3023, 'Ipuiuna', 11);
INSERT INTO city(id,name,id_state) VALUES(3024, 'Irai de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3025, 'Itabira', 11);
INSERT INTO city(id,name,id_state) VALUES(3026, 'Itabirinha de Mantena', 11);
INSERT INTO city(id,name,id_state) VALUES(3027, 'Itabirito', 11);
INSERT INTO city(id,name,id_state) VALUES(3028, 'Itaboca', 11);
INSERT INTO city(id,name,id_state) VALUES(3029, 'Itacambira', 11);
INSERT INTO city(id,name,id_state) VALUES(3030, 'Itacarambi', 11);
INSERT INTO city(id,name,id_state) VALUES(3031, 'Itaci', 11);
INSERT INTO city(id,name,id_state) VALUES(3032, 'Itacolomi', 11);
INSERT INTO city(id,name,id_state) VALUES(3033, 'Itaguara', 11);
INSERT INTO city(id,name,id_state) VALUES(3034, 'Itaim', 11);
INSERT INTO city(id,name,id_state) VALUES(3035, 'Itaipe', 11);
INSERT INTO city(id,name,id_state) VALUES(3036, 'Itajuba', 11);
INSERT INTO city(id,name,id_state) VALUES(3037, 'Itajutiba', 11);
INSERT INTO city(id,name,id_state) VALUES(3038, 'Itamarandiba', 11);
INSERT INTO city(id,name,id_state) VALUES(3039, 'Itamarati', 11);
INSERT INTO city(id,name,id_state) VALUES(3040, 'Itamarati de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3041, 'Itambacuri', 11);
INSERT INTO city(id,name,id_state) VALUES(3042, 'Itambe do Mato Dentro', 11);
INSERT INTO city(id,name,id_state) VALUES(3043, 'Itamirim', 11);
INSERT INTO city(id,name,id_state) VALUES(3044, 'Itamogi', 11);
INSERT INTO city(id,name,id_state) VALUES(3045, 'Itamonte', 11);
INSERT INTO city(id,name,id_state) VALUES(3046, 'Itamuri', 11);
INSERT INTO city(id,name,id_state) VALUES(3047, 'Itanhandu', 11);
INSERT INTO city(id,name,id_state) VALUES(3048, 'Itanhomi', 11);
INSERT INTO city(id,name,id_state) VALUES(3049, 'Itaobim', 11);
INSERT INTO city(id,name,id_state) VALUES(3050, 'Itapagipe', 11);
INSERT INTO city(id,name,id_state) VALUES(3051, 'Itapanhoacanga', 11);
INSERT INTO city(id,name,id_state) VALUES(3052, 'Itapecerica', 11);
INSERT INTO city(id,name,id_state) VALUES(3053, 'Itapeva', 11);
INSERT INTO city(id,name,id_state) VALUES(3054, 'Itapiru', 11);
INSERT INTO city(id,name,id_state) VALUES(3055, 'Itapirucu', 11);
INSERT INTO city(id,name,id_state) VALUES(3056, 'Itatiaiucu', 11);
INSERT INTO city(id,name,id_state) VALUES(3057, 'Itau de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3058, 'Itauna', 11);
INSERT INTO city(id,name,id_state) VALUES(3059, 'Itauninha', 11);
INSERT INTO city(id,name,id_state) VALUES(3060, 'Itaverava', 11);
INSERT INTO city(id,name,id_state) VALUES(3061, 'Iterere', 11);
INSERT INTO city(id,name,id_state) VALUES(3062, 'Itinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3063, 'Itira', 11);
INSERT INTO city(id,name,id_state) VALUES(3064, 'Itueta', 11);
INSERT INTO city(id,name,id_state) VALUES(3065, 'Itui', 11);
INSERT INTO city(id,name,id_state) VALUES(3066, 'Ituiutaba', 11);
INSERT INTO city(id,name,id_state) VALUES(3067, 'Itumirim', 11);
INSERT INTO city(id,name,id_state) VALUES(3068, 'Iturama', 11);
INSERT INTO city(id,name,id_state) VALUES(3069, 'Itutinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3070, 'Jaboticatubas', 11);
INSERT INTO city(id,name,id_state) VALUES(3071, 'Jacarandira', 11);
INSERT INTO city(id,name,id_state) VALUES(3072, 'Jacare', 11);
INSERT INTO city(id,name,id_state) VALUES(3073, 'Jacinto', 11);
INSERT INTO city(id,name,id_state) VALUES(3074, 'Jacui', 11);
INSERT INTO city(id,name,id_state) VALUES(3075, 'Jacutinga', 11);
INSERT INTO city(id,name,id_state) VALUES(3076, 'Jaguaracu', 11);
INSERT INTO city(id,name,id_state) VALUES(3077, 'Jaguarao', 11);
INSERT INTO city(id,name,id_state) VALUES(3078, 'Jaguaritira', 11);
INSERT INTO city(id,name,id_state) VALUES(3079, 'Jaiba', 11);
INSERT INTO city(id,name,id_state) VALUES(3080, 'Jampruca', 11);
INSERT INTO city(id,name,id_state) VALUES(3081, 'Janauba', 11);
INSERT INTO city(id,name,id_state) VALUES(3082, 'Januaria', 11);
INSERT INTO city(id,name,id_state) VALUES(3083, 'Japaraiba', 11);
INSERT INTO city(id,name,id_state) VALUES(3084, 'Japonvar', 11);
INSERT INTO city(id,name,id_state) VALUES(3085, 'Jardinesia', 11);
INSERT INTO city(id,name,id_state) VALUES(3086, 'Jeceaba', 11);
INSERT INTO city(id,name,id_state) VALUES(3087, 'Jequeri', 11);
INSERT INTO city(id,name,id_state) VALUES(3088, 'Jequitai', 11);
INSERT INTO city(id,name,id_state) VALUES(3089, 'Jequitiba', 11);
INSERT INTO city(id,name,id_state) VALUES(3090, 'Jequitinhonha', 11);
INSERT INTO city(id,name,id_state) VALUES(3091, 'Jesuania', 11);
INSERT INTO city(id,name,id_state) VALUES(3092, 'Joaima', 11);
INSERT INTO city(id,name,id_state) VALUES(3093, 'Joanesia', 11);
INSERT INTO city(id,name,id_state) VALUES(3094, 'Joao Monlevade', 11);
INSERT INTO city(id,name,id_state) VALUES(3095, 'Joao Pinheiro', 11);
INSERT INTO city(id,name,id_state) VALUES(3096, 'Joaquim Felicio', 11);
INSERT INTO city(id,name,id_state) VALUES(3097, 'Jordania', 11);
INSERT INTO city(id,name,id_state) VALUES(3098, 'Jose Goncalves de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3099, 'Jose Raydam', 11);
INSERT INTO city(id,name,id_state) VALUES(3100, 'Joselandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3101, 'Josenopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3102, 'Juatuba', 11);
INSERT INTO city(id,name,id_state) VALUES(3103, 'Jubai', 11);
INSERT INTO city(id,name,id_state) VALUES(3104, 'Juiracu', 11);
INSERT INTO city(id,name,id_state) VALUES(3105, 'Juiz de Fora', 11);
INSERT INTO city(id,name,id_state) VALUES(3106, 'Junco de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3107, 'Juramento', 11);
INSERT INTO city(id,name,id_state) VALUES(3108, 'Jureia', 11);
INSERT INTO city(id,name,id_state) VALUES(3109, 'Juruaia', 11);
INSERT INTO city(id,name,id_state) VALUES(3110, 'Jurumirim', 11);
INSERT INTO city(id,name,id_state) VALUES(3111, 'Justinopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3112, 'Juvenilia', 11);
INSERT INTO city(id,name,id_state) VALUES(3113, 'Lacerdinha', 11);
INSERT INTO city(id,name,id_state) VALUES(3114, 'Ladainha', 11);
INSERT INTO city(id,name,id_state) VALUES(3115, 'Lagamar', 11);
INSERT INTO city(id,name,id_state) VALUES(3116, 'Lagoa Bonita', 11);
INSERT INTO city(id,name,id_state) VALUES(3117, 'Lagoa da Prata', 11);
INSERT INTO city(id,name,id_state) VALUES(3118, 'Lagoa dos Patos', 11);
INSERT INTO city(id,name,id_state) VALUES(3119, 'Lagoa Dourada', 11);
INSERT INTO city(id,name,id_state) VALUES(3120, 'Lagoa Formosa', 11);
INSERT INTO city(id,name,id_state) VALUES(3121, 'Lagoa Grande', 11);
INSERT INTO city(id,name,id_state) VALUES(3122, 'Lagoa Santa', 11);
INSERT INTO city(id,name,id_state) VALUES(3123, 'Lajinha', 11);
INSERT INTO city(id,name,id_state) VALUES(3124, 'Lambari', 11);
INSERT INTO city(id,name,id_state) VALUES(3125, 'Lamim', 11);
INSERT INTO city(id,name,id_state) VALUES(3126, 'Lamounier', 11);
INSERT INTO city(id,name,id_state) VALUES(3127, 'Lapinha', 11);
INSERT INTO city(id,name,id_state) VALUES(3128, 'Laranjal', 11);
INSERT INTO city(id,name,id_state) VALUES(3129, 'Laranjeiras de Caldas', 11);
INSERT INTO city(id,name,id_state) VALUES(3130, 'Lassance', 11);
INSERT INTO city(id,name,id_state) VALUES(3131, 'Lavras', 11);
INSERT INTO city(id,name,id_state) VALUES(3132, 'Leandro Ferreira', 11);
INSERT INTO city(id,name,id_state) VALUES(3133, 'Leme do Prado', 11);
INSERT INTO city(id,name,id_state) VALUES(3134, 'Leopoldina', 11);
INSERT INTO city(id,name,id_state) VALUES(3135, 'Levinopolis', 11);
INSERT INTO city(id,name,id_state) VALUES(3136, 'Liberdade', 11);
INSERT INTO city(id,name,id_state) VALUES(3137, 'Lima Duarte', 11);
INSERT INTO city(id,name,id_state) VALUES(3138, 'Limeira D''Oeste', 11);
INSERT INTO city(id,name,id_state) VALUES(3139, 'Limeira de Mantena', 11);
INSERT INTO city(id,name,id_state) VALUES(3140, 'Lobo Leite', 11);
INSERT INTO city(id,name,id_state) VALUES(3141, 'Lontra', 11);
INSERT INTO city(id,name,id_state) VALUES(3142, 'Lourenco Velho', 11);
INSERT INTO city(id,name,id_state) VALUES(3143, 'Lufa', 11);
INSERT INTO city(id,name,id_state) VALUES(3144, 'Luisburgo', 11);
INSERT INTO city(id,name,id_state) VALUES(3145, 'Luislandia', 11);
INSERT INTO city(id,name,id_state) VALUES(3146, 'Luiz Pires de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3147, 'Luizlandia do Oeste', 11);
INSERT INTO city(id,name,id_state) VALUES(3148, 'Luminarias', 11);
INSERT INTO city(id,name,id_state) VALUES(3149, 'Luminosa', 11);
INSERT INTO city(id,name,id_state) VALUES(3150, 'Luz', 11);
INSERT INTO city(id,name,id_state) VALUES(3151, 'Macaia', 11);
INSERT INTO city(id,name,id_state) VALUES(3152, 'Machacalis', 11);
INSERT INTO city(id,name,id_state) VALUES(3153, 'Machado', 11);
INSERT INTO city(id,name,id_state) VALUES(3154, 'Macuco de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3155, 'Madre de Deus de Minas', 11);
INSERT INTO city(id,name,id_state) VALUES(3156, 'Mae dos Homens', 11);
INSERT INTO city(id,name,id_state) VALUES(3157, 'Major Ezequiel', 11);
INSERT INTO city(id,name,id_state) VALUES(3158, 'Major Porto', 11);
INSERT INTO city(id,name,id_state) VALUES(3159, 'Malacacheta', 11);
INSERT INTO city(id,name,id_state) VALUES(3160, 'Mamonas', 11);
