INSERT INTO parents(id,initials,name) VALUES (1, 'BR','Brasil');

INSERT INTO state(id,name,initials,id_parents) VALUES(8, 'Espírito Santo', 'ES',1);

INSERT INTO city(id,name,id_state) VALUES(1697, 'Acioli', 8);
INSERT INTO city(id,name,id_state) VALUES(1698, 'Afonso Claudio', 8);
INSERT INTO city(id,name,id_state) VALUES(1699, 'Agha', 8);
INSERT INTO city(id,name,id_state) VALUES(1700, 'Água Doce do Norte', 8);
INSERT INTO city(id,name,id_state) VALUES(1701, 'Águia Branca', 8);
INSERT INTO city(id,name,id_state) VALUES(1702, 'Airituba', 8);
INSERT INTO city(id,name,id_state) VALUES(1703, 'Alegre', 8);
INSERT INTO city(id,name,id_state) VALUES(1704, 'Alfredo Chaves', 8);
INSERT INTO city(id,name,id_state) VALUES(1705, 'Alto Calcado', 8);
INSERT INTO city(id,name,id_state) VALUES(1706, 'Alto Caldeirão', 8);
INSERT INTO city(id,name,id_state) VALUES(1707, 'Alto Mutum Preto', 8);
INSERT INTO city(id,name,id_state) VALUES(1708, 'Alto Rio Novo', 8);
INSERT INTO city(id,name,id_state) VALUES(1709, 'Alto Santa Maria', 8);
INSERT INTO city(id,name,id_state) VALUES(1710, 'Anchieta', 8);
INSERT INTO city(id,name,id_state) VALUES(1711, 'Angelo Frechiani', 8);
INSERT INTO city(id,name,id_state) VALUES(1712, 'Anutiba', 8);
INSERT INTO city(id,name,id_state) VALUES(1713, 'Apiaca', 8);
INSERT INTO city(id,name,id_state) VALUES(1714, 'Aracatiba', 8);
INSERT INTO city(id,name,id_state) VALUES(1715, 'Arace', 8);
INSERT INTO city(id,name,id_state) VALUES(1716, 'Aracruz', 8);
INSERT INTO city(id,name,id_state) VALUES(1717, 'Aracui', 8);
INSERT INTO city(id,name,id_state) VALUES(1718, 'Araguaia', 8);
INSERT INTO city(id,name,id_state) VALUES(1719, 'Ararai', 8);
INSERT INTO city(id,name,id_state) VALUES(1720, 'Argolas', 8);
INSERT INTO city(id,name,id_state) VALUES(1721, 'Atilio Vivacqua', 8);
INSERT INTO city(id,name,id_state) VALUES(1722, 'Baia Nova', 8);
INSERT INTO city(id,name,id_state) VALUES(1723, 'Baixo Guandu', 8);
INSERT INTO city(id,name,id_state) VALUES(1724, 'Barra de Novo Brasil', 8);
INSERT INTO city(id,name,id_state) VALUES(1725, 'Barra de São Francisco', 8);
INSERT INTO city(id,name,id_state) VALUES(1726, 'Barra do Itapemirim', 8);
INSERT INTO city(id,name,id_state) VALUES(1727, 'Barra Nova', 8);
INSERT INTO city(id,name,id_state) VALUES(1728, 'Barra Seca', 8);
INSERT INTO city(id,name,id_state) VALUES(1729, 'Baunilha', 8);
INSERT INTO city(id,name,id_state) VALUES(1730, 'Bebedouro', 8);
INSERT INTO city(id,name,id_state) VALUES(1731, 'Boa Esperanca', 8);
INSERT INTO city(id,name,id_state) VALUES(1732, 'Boapaba', 8);
INSERT INTO city(id,name,id_state) VALUES(1733, 'Bom Jesus do Norte', 8);
INSERT INTO city(id,name,id_state) VALUES(1734, 'Braco do Rio', 8);
INSERT INTO city(id,name,id_state) VALUES(1735, 'Brejetuba', 8);
INSERT INTO city(id,name,id_state) VALUES(1736, 'Burarama', 8);
INSERT INTO city(id,name,id_state) VALUES(1737, 'Cachoeirinha de Itauna', 8);
INSERT INTO city(id,name,id_state) VALUES(1738, 'Cachoeiro de Itapemirim', 8);
INSERT INTO city(id,name,id_state) VALUES(1739, 'Cafe', 8);
INSERT INTO city(id,name,id_state) VALUES(1740, 'Calogi', 8);
INSERT INTO city(id,name,id_state) VALUES(1741, 'Camara', 8);
INSERT INTO city(id,name,id_state) VALUES(1742, 'Carapina', 8);
INSERT INTO city(id,name,id_state) VALUES(1743, 'Cariacica', 8);
INSERT INTO city(id,name,id_state) VALUES(1744, 'Castelo', 8);
INSERT INTO city(id,name,id_state) VALUES(1745, 'Celina', 8);
INSERT INTO city(id,name,id_state) VALUES(1746, 'Colatina', 8);
INSERT INTO city(id,name,id_state) VALUES(1747, 'Conceicao da Barra', 8);
INSERT INTO city(id,name,id_state) VALUES(1748, 'Conceicao do Castelo', 8);
INSERT INTO city(id,name,id_state) VALUES(1749, 'Conceicao do Muqui', 8);
INSERT INTO city(id,name,id_state) VALUES(1750, 'Conduru', 8);
INSERT INTO city(id,name,id_state) VALUES(1751, 'Coqueiral', 8);
INSERT INTO city(id,name,id_state) VALUES(1752, 'Corrego D''Agua', 8);
INSERT INTO city(id,name,id_state) VALUES(1753, 'Cotaxe', 8);
INSERT INTO city(id,name,id_state) VALUES(1754, 'Cristal do Norte', 8);
INSERT INTO city(id,name,id_state) VALUES(1755, 'Crubixa', 8);
INSERT INTO city(id,name,id_state) VALUES(1756, 'Desengano', 8);
INSERT INTO city(id,name,id_state) VALUES(1757, 'Divino de Sao Lourenco', 8);
INSERT INTO city(id,name,id_state) VALUES(1758, 'Djalma Coutinho', 8);
INSERT INTO city(id,name,id_state) VALUES(1759, 'Domingos Martins', 8);
INSERT INTO city(id,name,id_state) VALUES(1760, 'Dona America', 8);
INSERT INTO city(id,name,id_state) VALUES(1761, 'Dores do Rio Preto', 8);
INSERT INTO city(id,name,id_state) VALUES(1762, 'Duas Barras', 8);
INSERT INTO city(id,name,id_state) VALUES(1763, 'Ecoporanga', 8);
INSERT INTO city(id,name,id_state) VALUES(1764, 'Estrela do Norte', 8);
INSERT INTO city(id,name,id_state) VALUES(1765, 'Fartura', 8);
INSERT INTO city(id,name,id_state) VALUES(1766, 'Fazenda Guandu', 8);
INSERT INTO city(id,name,id_state) VALUES(1767, 'Fundao', 8);
INSERT INTO city(id,name,id_state) VALUES(1768, 'Garrafao', 8);
INSERT INTO city(id,name,id_state) VALUES(1769, 'Gironda', 8);
INSERT INTO city(id,name,id_state) VALUES(1770, 'Goiabeiras', 8);
INSERT INTO city(id,name,id_state) VALUES(1771, 'Governador Lacerda de Aguiar', 8);
INSERT INTO city(id,name,id_state) VALUES(1772, 'Governador Lindenberg', 8);
INSERT INTO city(id,name,id_state) VALUES(1773, 'Graca Aranha', 8);
INSERT INTO city(id,name,id_state) VALUES(1774, 'Guacui', 8);
INSERT INTO city(id,name,id_state) VALUES(1775, 'Guarana', 8);
INSERT INTO city(id,name,id_state) VALUES(1776, 'Guarapari', 8);
INSERT INTO city(id,name,id_state) VALUES(1777, 'Guararema', 8);
INSERT INTO city(id,name,id_state) VALUES(1778, 'Ibatiba', 8);
INSERT INTO city(id,name,id_state) VALUES(1779, 'Ibes', 8);
INSERT INTO city(id,name,id_state) VALUES(1780, 'Ibicaba', 8);
INSERT INTO city(id,name,id_state) VALUES(1781, 'Ibiracu', 8);
INSERT INTO city(id,name,id_state) VALUES(1782, 'Ibitirama', 8);
INSERT INTO city(id,name,id_state) VALUES(1783, 'Ibitirui', 8);
INSERT INTO city(id,name,id_state) VALUES(1784, 'Ibituba', 8);
INSERT INTO city(id,name,id_state) VALUES(1785, 'Iconha', 8);
INSERT INTO city(id,name,id_state) VALUES(1786, 'Imburana', 8);
INSERT INTO city(id,name,id_state) VALUES(1787, 'Iriritiba', 8);
INSERT INTO city(id,name,id_state) VALUES(1788, 'Irundi', 8);
INSERT INTO city(id,name,id_state) VALUES(1789, 'Irupi', 8);
INSERT INTO city(id,name,id_state) VALUES(1790, 'Isabel', 8);
INSERT INTO city(id,name,id_state) VALUES(1791, 'Itabaiana', 8);
INSERT INTO city(id,name,id_state) VALUES(1792, 'Itacu', 8);
INSERT INTO city(id,name,id_state) VALUES(1793, 'Itaguacu', 8);
INSERT INTO city(id,name,id_state) VALUES(1794, 'Itaici', 8);
INSERT INTO city(id,name,id_state) VALUES(1795, 'Itaimbe', 8);
INSERT INTO city(id,name,id_state) VALUES(1796, 'Itaipava', 8);
INSERT INTO city(id,name,id_state) VALUES(1797, 'Itamira', 8);
INSERT INTO city(id,name,id_state) VALUES(1798, 'Itaoca', 8);
INSERT INTO city(id,name,id_state) VALUES(1799, 'Itapecoa', 8);
INSERT INTO city(id,name,id_state) VALUES(1800, 'Itapemirim', 8);
INSERT INTO city(id,name,id_state) VALUES(1801, 'Itaperuna', 8);
INSERT INTO city(id,name,id_state) VALUES(1802, 'Itapina', 8);
INSERT INTO city(id,name,id_state) VALUES(1803, 'Itaquari', 8);
INSERT INTO city(id,name,id_state) VALUES(1804, 'Itarana', 8);
INSERT INTO city(id,name,id_state) VALUES(1805, 'Itaunas', 8);
INSERT INTO city(id,name,id_state) VALUES(1806, 'Itauninhas', 8);
INSERT INTO city(id,name,id_state) VALUES(1807, 'Iuna', 8);
INSERT INTO city(id,name,id_state) VALUES(1808, 'Jabaquara', 8);
INSERT INTO city(id,name,id_state) VALUES(1809, 'Jacaraipe', 8);
INSERT INTO city(id,name,id_state) VALUES(1810, 'Jacigua', 8);
INSERT INTO city(id,name,id_state) VALUES(1811, 'Jacupemba', 8);
INSERT INTO city(id,name,id_state) VALUES(1812, 'Jaguare', 8);
INSERT INTO city(id,name,id_state) VALUES(1813, 'Jeronimo Monteiro', 8);
INSERT INTO city(id,name,id_state) VALUES(1814, 'Joacuba', 8);
INSERT INTO city(id,name,id_state) VALUES(1815, 'Joao Neiva', 8);
INSERT INTO city(id,name,id_state) VALUES(1816, 'Joatuba', 8);
INSERT INTO city(id,name,id_state) VALUES(1817, 'Jose Carlos', 8);
INSERT INTO city(id,name,id_state) VALUES(1818, 'Jucu', 8);
INSERT INTO city(id,name,id_state) VALUES(1819, 'Lajinha', 8);
INSERT INTO city(id,name,id_state) VALUES(1820, 'Laranja da Terra', 8);
INSERT INTO city(id,name,id_state) VALUES(1821, 'Linhares', 8);
INSERT INTO city(id,name,id_state) VALUES(1822, 'Mangarai', 8);
INSERT INTO city(id,name,id_state) VALUES(1823, 'Mantenopolis', 8);
INSERT INTO city(id,name,id_state) VALUES(1824, 'Marataizes', 8);
INSERT INTO city(id,name,id_state) VALUES(1825, 'Marechal Floriano', 8);
INSERT INTO city(id,name,id_state) VALUES(1826, 'Marilandia', 8);
INSERT INTO city(id,name,id_state) VALUES(1827, 'Matilde', 8);
INSERT INTO city(id,name,id_state) VALUES(1828, 'Melgaco', 8);
INSERT INTO city(id,name,id_state) VALUES(1829, 'Menino Jesus', 8);
INSERT INTO city(id,name,id_state) VALUES(1830, 'Mimoso do Sul', 8);
INSERT INTO city(id,name,id_state) VALUES(1831, 'Montanha', 8);
INSERT INTO city(id,name,id_state) VALUES(1832, 'Monte Carmelo do Rio Novo', 8);
INSERT INTO city(id,name,id_state) VALUES(1833, 'Monte Sinai', 8);
INSERT INTO city(id,name,id_state) VALUES(1834, 'Mucurici', 8);
INSERT INTO city(id,name,id_state) VALUES(1835, 'Mundo Novo', 8);
INSERT INTO city(id,name,id_state) VALUES(1836, 'Muniz Freire', 8);
INSERT INTO city(id,name,id_state) VALUES(1837, 'Muqui', 8);
INSERT INTO city(id,name,id_state) VALUES(1838, 'Nestor Gomes', 8);
INSERT INTO city(id,name,id_state) VALUES(1839, 'Nova Almeida', 8);
INSERT INTO city(id,name,id_state) VALUES(1840, 'Nova Canaa', 8);
INSERT INTO city(id,name,id_state) VALUES(1841, 'Nova Venecia', 8);
INSERT INTO city(id,name,id_state) VALUES(1842, 'Nova Verona', 8);
INSERT INTO city(id,name,id_state) VALUES(1843, 'Novo Brasil', 8);
INSERT INTO city(id,name,id_state) VALUES(1844, 'Novo Horizonte', 8);
INSERT INTO city(id,name,id_state) VALUES(1845, 'Pacotuba', 8);
INSERT INTO city(id,name,id_state) VALUES(1846, 'Paineiras', 8);
INSERT INTO city(id,name,id_state) VALUES(1847, 'Palmerino', 8);
INSERT INTO city(id,name,id_state) VALUES(1848, 'Pancas', 8);
INSERT INTO city(id,name,id_state) VALUES(1849, 'Paraju', 8);
INSERT INTO city(id,name,id_state) VALUES(1850, 'Paulista', 8);
INSERT INTO city(id,name,id_state) VALUES(1851, 'Pedro Canario', 8);
INSERT INTO city(id,name,id_state) VALUES(1852, 'Pendanga', 8);
INSERT INTO city(id,name,id_state) VALUES(1853, 'Pequia', 8);
INSERT INTO city(id,name,id_state) VALUES(1854, 'Perdicao', 8);
INSERT INTO city(id,name,id_state) VALUES(1855, 'Piacu', 8);
INSERT INTO city(id,name,id_state) VALUES(1856, 'Pinheiros', 8);
INSERT INTO city(id,name,id_state) VALUES(1857, 'Piracema', 8);
INSERT INTO city(id,name,id_state) VALUES(1858, 'Piuma', 8);
INSERT INTO city(id,name,id_state) VALUES(1859, 'Ponte de Itabapoana', 8);
INSERT INTO city(id,name,id_state) VALUES(1860, 'Pontoes', 8);
INSERT INTO city(id,name,id_state) VALUES(1861, 'Poranga', 8);
INSERT INTO city(id,name,id_state) VALUES(1862, 'Porto Barra do Riacho', 8);
INSERT INTO city(id,name,id_state) VALUES(1863, 'Praia Grande', 8);
INSERT INTO city(id,name,id_state) VALUES(1864, 'Presidente Kennedy', 8);
INSERT INTO city(id,name,id_state) VALUES(1865, 'Princesa', 8);
INSERT INTO city(id,name,id_state) VALUES(1866, 'Queimado', 8);
INSERT INTO city(id,name,id_state) VALUES(1867, 'Quilometro 14 do Mutum', 8);
INSERT INTO city(id,name,id_state) VALUES(1868, 'Regencia', 8);
INSERT INTO city(id,name,id_state) VALUES(1869, 'Riacho', 8);
INSERT INTO city(id,name,id_state) VALUES(1870, 'Ribeirao do Cristo', 8);
INSERT INTO city(id,name,id_state) VALUES(1871, 'Rio Bananal', 8);
INSERT INTO city(id,name,id_state) VALUES(1872, 'Rio Calcado', 8);
INSERT INTO city(id,name,id_state) VALUES(1873, 'Rio Muqui', 8);
INSERT INTO city(id,name,id_state) VALUES(1874, 'Rio Novo do Sul', 8);
INSERT INTO city(id,name,id_state) VALUES(1875, 'Rio Preto', 8);
INSERT INTO city(id,name,id_state) VALUES(1876, 'Rive', 8);
INSERT INTO city(id,name,id_state) VALUES(1877, 'Sagrada Familia', 8);
INSERT INTO city(id,name,id_state) VALUES(1878, 'Santa Angelica', 8);
INSERT INTO city(id,name,id_state) VALUES(1879, 'Santa Cruz', 8);
INSERT INTO city(id,name,id_state) VALUES(1880, 'Santa Julia', 8);
INSERT INTO city(id,name,id_state) VALUES(1881, 'Santa Leopoldina', 8);
INSERT INTO city(id,name,id_state) VALUES(1882, 'Santa Luzia de Mantenopolis', 8);
INSERT INTO city(id,name,id_state) VALUES(1883, 'Santa Luzia do Azul', 8);
INSERT INTO city(id,name,id_state) VALUES(1884, 'Santa Luzia do Norte', 8);
INSERT INTO city(id,name,id_state) VALUES(1885, 'Santa Maria de Jetiba', 8);
INSERT INTO city(id,name,id_state) VALUES(1886, 'Santa Marta', 8);
INSERT INTO city(id,name,id_state) VALUES(1887, 'Santa Teresa', 8);
INSERT INTO city(id,name,id_state) VALUES(1888, 'Santa Terezinha', 8);
INSERT INTO city(id,name,id_state) VALUES(1889, 'Santissima Trindade', 8);
INSERT INTO city(id,name,id_state) VALUES(1890, 'Santo Agostinho', 8);
INSERT INTO city(id,name,id_state) VALUES(1891, 'Santo Antonio', 8);
INSERT INTO city(id,name,id_state) VALUES(1892, 'Santo Antonio do Canaa', 8);
INSERT INTO city(id,name,id_state) VALUES(1893, 'Santo Antonio do Muqui', 8);
INSERT INTO city(id,name,id_state) VALUES(1894, 'Santo Antonio do Pousalegre', 8);
INSERT INTO city(id,name,id_state) VALUES(1895, 'Santo Antonio do Quinze', 8);
INSERT INTO city(id,name,id_state) VALUES(1896, 'Sao Domingos do Norte', 8);
INSERT INTO city(id,name,id_state) VALUES(1897, 'Sao Francisco do Novo Brasil', 8);
INSERT INTO city(id,name,id_state) VALUES(1898, 'Sao Gabriel da Palha', 8);
INSERT INTO city(id,name,id_state) VALUES(1899, 'Sao Geraldo', 8);
INSERT INTO city(id,name,id_state) VALUES(1900, 'Sao Jacinto', 8);
INSERT INTO city(id,name,id_state) VALUES(1901, 'Sao Joao de Petropolis', 8);
INSERT INTO city(id,name,id_state) VALUES(1902, 'Sao Joao de Vicosa', 8);
INSERT INTO city(id,name,id_state) VALUES(1903, 'Sao Joao do Sobrado', 8);
INSERT INTO city(id,name,id_state) VALUES(1904, 'Sao Jorge da Barra Seca', 8);
INSERT INTO city(id,name,id_state) VALUES(1905, 'Sao Jorge do Tiradentes', 8);
INSERT INTO city(id,name,id_state) VALUES(1906, 'Sao Jose das Torres', 8);
INSERT INTO city(id,name,id_state) VALUES(1907, 'Sao Jose do Calcado', 8);
INSERT INTO city(id,name,id_state) VALUES(1908, 'Sao Jose do Sobradinho', 8);
INSERT INTO city(id,name,id_state) VALUES(1909, 'Sao Mateus', 8);
INSERT INTO city(id,name,id_state) VALUES(1910, 'Sao Pedro de Itabapoana', 8);
INSERT INTO city(id,name,id_state) VALUES(1911, 'Sao Pedro de Rates', 8);
INSERT INTO city(id,name,id_state) VALUES(1912, 'Sao Rafael', 8);
INSERT INTO city(id,name,id_state) VALUES(1913, 'Sao Roque', 8);
INSERT INTO city(id,name,id_state) VALUES(1914, 'Sao Tiago', 8);
INSERT INTO city(id,name,id_state) VALUES(1915, 'Sao Torquato', 8);
INSERT INTO city(id,name,id_state) VALUES(1916, 'Sapucaia', 8);
INSERT INTO city(id,name,id_state) VALUES(1917, 'Serra', 8);
INSERT INTO city(id,name,id_state) VALUES(1918, 'Serra Pelada', 8);
INSERT INTO city(id,name,id_state) VALUES(1919, 'Sobreiro', 8);
INSERT INTO city(id,name,id_state) VALUES(1920, 'Timbui', 8);
INSERT INTO city(id,name,id_state) VALUES(1921, 'Todos Os Santos', 8);
INSERT INTO city(id,name,id_state) VALUES(1922, 'Urania', 8);
INSERT INTO city(id,name,id_state) VALUES(1923, 'Valerio', 8);
INSERT INTO city(id,name,id_state) VALUES(1924, 'Vargem Alta', 8);
INSERT INTO city(id,name,id_state) VALUES(1925, 'Vargem Grande do Soturno', 8);
INSERT INTO city(id,name,id_state) VALUES(1926, 'Venda Nova do Imigrante', 8);
INSERT INTO city(id,name,id_state) VALUES(1927, 'Viana', 8);
INSERT INTO city(id,name,id_state) VALUES(1928, 'Vieira Machado', 8);
INSERT INTO city(id,name,id_state) VALUES(1929, 'Vila Nelita', 8);
INSERT INTO city(id,name,id_state) VALUES(1930, 'Vila Nova de Bananal', 8);
INSERT INTO city(id,name,id_state) VALUES(1931, 'Vila Pavao', 8);
INSERT INTO city(id,name,id_state) VALUES(1932, 'Vila Velha', 8);
INSERT INTO city(id,name,id_state) VALUES(1933, 'Vila Verde', 8);
INSERT INTO city(id,name,id_state) VALUES(1934, 'Vinhatico', 8);
INSERT INTO city(id,name,id_state) VALUES(1935, 'Vinte e Cinco de Julho', 8);
INSERT INTO city(id,name,id_state) VALUES(1936, 'Vitoria', 8);
