INSERT INTO state(id,name,initials,id_parents) VALUES(19, 'Rio de Janeiro', 'RJ',1);

INSERT INTO city(id,name,id_state) VALUES(6406, 'Abarracamento', 19);
INSERT INTO city(id,name,id_state) VALUES(6407, 'Abraao', 19);
INSERT INTO city(id,name,id_state) VALUES(6408, 'Afonso Arinos', 19);
INSERT INTO city(id,name,id_state) VALUES(6409, 'Agulhas Negras', 19);
INSERT INTO city(id,name,id_state) VALUES(6410, 'Amparo', 19);
INSERT INTO city(id,name,id_state) VALUES(6411, 'Andrade Pinto', 19);
INSERT INTO city(id,name,id_state) VALUES(6412, 'Angra dos Reis', 19);
INSERT INTO city(id,name,id_state) VALUES(6413, 'Anta', 19);
INSERT INTO city(id,name,id_state) VALUES(6414, 'Aperibe', 19);
INSERT INTO city(id,name,id_state) VALUES(6415, 'Araruama', 19);
INSERT INTO city(id,name,id_state) VALUES(6416, 'Areal', 19);
INSERT INTO city(id,name,id_state) VALUES(6417, 'Armacao dos Buzios', 19);
INSERT INTO city(id,name,id_state) VALUES(6418, 'Arraial do Cabo', 19);
INSERT INTO city(id,name,id_state) VALUES(6419, 'Arrozal', 19);
INSERT INTO city(id,name,id_state) VALUES(6420, 'Avelar', 19);
INSERT INTO city(id,name,id_state) VALUES(6421, 'Bacaxa', 19);
INSERT INTO city(id,name,id_state) VALUES(6422, 'Baltazar', 19);
INSERT INTO city(id,name,id_state) VALUES(6423, 'Banquete', 19);
INSERT INTO city(id,name,id_state) VALUES(6424, 'Barao de Juparana', 19);
INSERT INTO city(id,name,id_state) VALUES(6425, 'Barcelos', 19);
INSERT INTO city(id,name,id_state) VALUES(6426, 'Barra Alegre', 19);
INSERT INTO city(id,name,id_state) VALUES(6427, 'Barra de Macae', 19);
INSERT INTO city(id,name,id_state) VALUES(6428, 'Barra de Sao Joao', 19);
INSERT INTO city(id,name,id_state) VALUES(6429, 'Barra do Pirai', 19);
INSERT INTO city(id,name,id_state) VALUES(6430, 'Barra Mansa', 19);
INSERT INTO city(id,name,id_state) VALUES(6431, 'Barra Seca', 19);
INSERT INTO city(id,name,id_state) VALUES(6432, 'Belford Roxo', 19);
INSERT INTO city(id,name,id_state) VALUES(6433, 'Bemposta', 19);
INSERT INTO city(id,name,id_state) VALUES(6434, 'Boa Esperanca', 19);
INSERT INTO city(id,name,id_state) VALUES(6435, 'Boa Sorte', 19);
INSERT INTO city(id,name,id_state) VALUES(6436, 'Boa Ventura', 19);
INSERT INTO city(id,name,id_state) VALUES(6437, 'Bom Jardim', 19);
INSERT INTO city(id,name,id_state) VALUES(6438, 'Bom Jesus do Itabapoana', 19);
INSERT INTO city(id,name,id_state) VALUES(6439, 'Bom Jesus do Querendo', 19);
INSERT INTO city(id,name,id_state) VALUES(6440, 'Cabo Frio', 19);
INSERT INTO city(id,name,id_state) VALUES(6441, 'Cabucu', 19);
INSERT INTO city(id,name,id_state) VALUES(6442, 'Cachoeiras de Macacu', 19);
INSERT INTO city(id,name,id_state) VALUES(6443, 'Cachoeiros', 19);
INSERT INTO city(id,name,id_state) VALUES(6444, 'Calheiros', 19);
INSERT INTO city(id,name,id_state) VALUES(6445, 'Cambiasca', 19);
INSERT INTO city(id,name,id_state) VALUES(6446, 'Cambuci', 19);
INSERT INTO city(id,name,id_state) VALUES(6447, 'Campo do Coelho', 19);
INSERT INTO city(id,name,id_state) VALUES(6448, 'Campos dos Goitacazes', 19);
INSERT INTO city(id,name,id_state) VALUES(6449, 'Campos Elyseos', 19);
INSERT INTO city(id,name,id_state) VALUES(6450, 'Cantagalo', 19);
INSERT INTO city(id,name,id_state) VALUES(6451, 'Carabucu', 19);
INSERT INTO city(id,name,id_state) VALUES(6452, 'Carapebus', 19);
INSERT INTO city(id,name,id_state) VALUES(6453, 'Cardoso Moreira', 19);
INSERT INTO city(id,name,id_state) VALUES(6454, 'Carmo', 19);
INSERT INTO city(id,name,id_state) VALUES(6455, 'Cascatinha', 19);
INSERT INTO city(id,name,id_state) VALUES(6456, 'Casimiro de Abreu', 19);
INSERT INTO city(id,name,id_state) VALUES(6457, 'Cava', 19);
INSERT INTO city(id,name,id_state) VALUES(6458, 'Coelho da Rocha', 19);
INSERT INTO city(id,name,id_state) VALUES(6459, 'Colonia', 19);
INSERT INTO city(id,name,id_state) VALUES(6460, 'Comendador Levy Gasparian', 19);
INSERT INTO city(id,name,id_state) VALUES(6461, 'Comendador Venancio', 19);
INSERT INTO city(id,name,id_state) VALUES(6462, 'Conceicao de Jacarei', 19);
INSERT INTO city(id,name,id_state) VALUES(6463, 'Conceicao de Macabu', 19);
INSERT INTO city(id,name,id_state) VALUES(6464, 'Conrado', 19);
INSERT INTO city(id,name,id_state) VALUES(6465, 'Conselheiro Paulino', 19);
INSERT INTO city(id,name,id_state) VALUES(6466, 'Conservatoria', 19);
INSERT INTO city(id,name,id_state) VALUES(6467, 'Cordeiro', 19);
INSERT INTO city(id,name,id_state) VALUES(6468, 'Coroa Grande', 19);
INSERT INTO city(id,name,id_state) VALUES(6469, 'Correas', 19);
INSERT INTO city(id,name,id_state) VALUES(6470, 'Corrego da Prata', 19);
INSERT INTO city(id,name,id_state) VALUES(6471, 'Corrego do Ouro', 19);
INSERT INTO city(id,name,id_state) VALUES(6472, 'Correntezas', 19);
INSERT INTO city(id,name,id_state) VALUES(6473, 'Cunhambebe', 19);
INSERT INTO city(id,name,id_state) VALUES(6474, 'Dorandia', 19);
INSERT INTO city(id,name,id_state) VALUES(6475, 'Dores de Macabu', 19);
INSERT INTO city(id,name,id_state) VALUES(6476, 'Doutor Elias', 19);
INSERT INTO city(id,name,id_state) VALUES(6477, 'Doutor Loreti', 19);
INSERT INTO city(id,name,id_state) VALUES(6478, 'Duas Barras', 19);
INSERT INTO city(id,name,id_state) VALUES(6479, 'Duque de Caxias', 19);
INSERT INTO city(id,name,id_state) VALUES(6480, 'Engenheiro Passos', 19);
INSERT INTO city(id,name,id_state) VALUES(6481, 'Engenheiro Paulo de Frontin', 19);
INSERT INTO city(id,name,id_state) VALUES(6482, 'Engenheiro Pedreira', 19);
INSERT INTO city(id,name,id_state) VALUES(6483, 'Estrada Nova', 19);
INSERT INTO city(id,name,id_state) VALUES(6484, 'Euclidelandia', 19);
INSERT INTO city(id,name,id_state) VALUES(6485, 'Falcao', 19);
INSERT INTO city(id,name,id_state) VALUES(6486, 'Floriano', 19);
INSERT INTO city(id,name,id_state) VALUES(6487, 'Fumaca', 19);
INSERT INTO city(id,name,id_state) VALUES(6488, 'Funil', 19);
INSERT INTO city(id,name,id_state) VALUES(6489, 'Gavioes', 19);
INSERT INTO city(id,name,id_state) VALUES(6490, 'Getulandia', 19);
INSERT INTO city(id,name,id_state) VALUES(6491, 'Glicerio', 19);
INSERT INTO city(id,name,id_state) VALUES(6492, 'Goitacazes', 19);
INSERT INTO city(id,name,id_state) VALUES(6493, 'Governador Portela', 19);
INSERT INTO city(id,name,id_state) VALUES(6494, 'Guapimirim', 19);
INSERT INTO city(id,name,id_state) VALUES(6495, 'Guia de Pacobaiba', 19);
INSERT INTO city(id,name,id_state) VALUES(6496, 'Ibitiguacu', 19);
INSERT INTO city(id,name,id_state) VALUES(6497, 'Ibitioca', 19);
INSERT INTO city(id,name,id_state) VALUES(6498, 'Ibituporanga', 19);
INSERT INTO city(id,name,id_state) VALUES(6499, 'Iguaba Grande', 19);
INSERT INTO city(id,name,id_state) VALUES(6500, 'Imbarie', 19);
INSERT INTO city(id,name,id_state) VALUES(6501, 'Inconfidencia', 19);
INSERT INTO city(id,name,id_state) VALUES(6502, 'Inhomirim', 19);
INSERT INTO city(id,name,id_state) VALUES(6503, 'Inoa', 19);
INSERT INTO city(id,name,id_state) VALUES(6504, 'Ipiabas', 19);
INSERT INTO city(id,name,id_state) VALUES(6505, 'Ipiiba', 19);
INSERT INTO city(id,name,id_state) VALUES(6506, 'Ipuca', 19);
INSERT INTO city(id,name,id_state) VALUES(6507, 'Itabapoana', 19);
INSERT INTO city(id,name,id_state) VALUES(6508, 'Itaborai', 19);
INSERT INTO city(id,name,id_state) VALUES(6509, 'Itacurussa', 19);
INSERT INTO city(id,name,id_state) VALUES(6510, 'Itaguai', 19);
INSERT INTO city(id,name,id_state) VALUES(6511, 'Itaipava', 19);
INSERT INTO city(id,name,id_state) VALUES(6512, 'Itaipu', 19);
INSERT INTO city(id,name,id_state) VALUES(6513, 'Itajara', 19);
INSERT INTO city(id,name,id_state) VALUES(6514, 'Italva', 19);
INSERT INTO city(id,name,id_state) VALUES(6515, 'Itambi', 19);
INSERT INTO city(id,name,id_state) VALUES(6516, 'Itaocara', 19);
INSERT INTO city(id,name,id_state) VALUES(6517, 'Itaperuna', 19);
INSERT INTO city(id,name,id_state) VALUES(6518, 'Itatiaia', 19);
INSERT INTO city(id,name,id_state) VALUES(6519, 'Jacuecanga', 19);
INSERT INTO city(id,name,id_state) VALUES(6520, 'Jaguarembe', 19);
INSERT INTO city(id,name,id_state) VALUES(6521, 'Jamapara', 19);
INSERT INTO city(id,name,id_state) VALUES(6522, 'Japeri', 19);
INSERT INTO city(id,name,id_state) VALUES(6523, 'Japuiba', 19);
INSERT INTO city(id,name,id_state) VALUES(6524, 'Laje do Muriae', 19);
INSERT INTO city(id,name,id_state) VALUES(6525, 'Laranjais', 19);
INSERT INTO city(id,name,id_state) VALUES(6526, 'Lidice', 19);
INSERT INTO city(id,name,id_state) VALUES(6527, 'Lumiar', 19);
INSERT INTO city(id,name,id_state) VALUES(6528, 'Macabuzinho', 19);
INSERT INTO city(id,name,id_state) VALUES(6529, 'Macae', 19);
INSERT INTO city(id,name,id_state) VALUES(6530, 'Macuco', 19);
INSERT INTO city(id,name,id_state) VALUES(6531, 'Mage', 19);
INSERT INTO city(id,name,id_state) VALUES(6532, 'Mambucaba', 19);
INSERT INTO city(id,name,id_state) VALUES(6533, 'Mangaratiba', 19);
INSERT INTO city(id,name,id_state) VALUES(6534, 'Maniva', 19);
INSERT INTO city(id,name,id_state) VALUES(6535, 'Manoel Ribeiro', 19);
INSERT INTO city(id,name,id_state) VALUES(6536, 'Manuel Duarte', 19);
INSERT INTO city(id,name,id_state) VALUES(6537, 'Marangatu', 19);
INSERT INTO city(id,name,id_state) VALUES(6538, 'Marica', 19);
INSERT INTO city(id,name,id_state) VALUES(6539, 'Mendes', 19);
INSERT INTO city(id,name,id_state) VALUES(6540, 'Mesquita', 19);
INSERT INTO city(id,name,id_state) VALUES(6541, 'Miguel Pereira', 19);
INSERT INTO city(id,name,id_state) VALUES(6542, 'Miracema', 19);
INSERT INTO city(id,name,id_state) VALUES(6543, 'Monera', 19);
INSERT INTO city(id,name,id_state) VALUES(6544, 'Monjolo', 19);
INSERT INTO city(id,name,id_state) VALUES(6545, 'Monte Alegre', 19);
INSERT INTO city(id,name,id_state) VALUES(6546, 'Monte Verde', 19);
INSERT INTO city(id,name,id_state) VALUES(6547, 'Monumento', 19);
INSERT INTO city(id,name,id_state) VALUES(6548, 'Morangaba', 19);
INSERT INTO city(id,name,id_state) VALUES(6549, 'Morro do Coco', 19);
INSERT INTO city(id,name,id_state) VALUES(6550, 'Morro Grande', 19);
INSERT INTO city(id,name,id_state) VALUES(6551, 'Mussurepe', 19);
INSERT INTO city(id,name,id_state) VALUES(6552, 'Natividade', 19);
INSERT INTO city(id,name,id_state) VALUES(6553, 'Neves', 19);
INSERT INTO city(id,name,id_state) VALUES(6554, 'Nhunguacu', 19);
INSERT INTO city(id,name,id_state) VALUES(6555, 'Nilopolis', 19);
INSERT INTO city(id,name,id_state) VALUES(6556, 'Niteroi', 19);
INSERT INTO city(id,name,id_state) VALUES(6557, 'Nossa Senhora da Aparecida', 19);
INSERT INTO city(id,name,id_state) VALUES(6558, 'Nossa Senhora da Penha', 19);
INSERT INTO city(id,name,id_state) VALUES(6559, 'Nossa Senhora do Amparo', 19);
INSERT INTO city(id,name,id_state) VALUES(6560, 'Nova Friburgo', 19);
INSERT INTO city(id,name,id_state) VALUES(6561, 'Nova Iguacu', 19);
INSERT INTO city(id,name,id_state) VALUES(6562, 'Olinda', 19);
INSERT INTO city(id,name,id_state) VALUES(6563, 'Ourania', 19);
INSERT INTO city(id,name,id_state) VALUES(6564, 'Papucaia', 19);
INSERT INTO city(id,name,id_state) VALUES(6565, 'Paquequer Pequeno', 19);
INSERT INTO city(id,name,id_state) VALUES(6566, 'Paracambi', 19);
INSERT INTO city(id,name,id_state) VALUES(6567, 'Paraiba do Sul', 19);
INSERT INTO city(id,name,id_state) VALUES(6568, 'Paraiso do Tobias', 19);
INSERT INTO city(id,name,id_state) VALUES(6569, 'Paraoquena', 19);
INSERT INTO city(id,name,id_state) VALUES(6570, 'Parapeuna', 19);
INSERT INTO city(id,name,id_state) VALUES(6571, 'Parati', 19);
INSERT INTO city(id,name,id_state) VALUES(6572, 'Parati Mirim', 19);
INSERT INTO city(id,name,id_state) VALUES(6573, 'Passa Tres', 19);
INSERT INTO city(id,name,id_state) VALUES(6574, 'Paty do Alferes', 19);
INSERT INTO city(id,name,id_state) VALUES(6575, 'Pedra Selada', 19);
INSERT INTO city(id,name,id_state) VALUES(6576, 'Pedro do Rio', 19);
INSERT INTO city(id,name,id_state) VALUES(6577, 'Penedo', 19);
INSERT INTO city(id,name,id_state) VALUES(6578, 'Pentagna', 19);
INSERT INTO city(id,name,id_state) VALUES(6579, 'Petropolis', 19);
INSERT INTO city(id,name,id_state) VALUES(6580, 'Piabeta', 19);
INSERT INTO city(id,name,id_state) VALUES(6581, 'Piao', 19);
INSERT INTO city(id,name,id_state) VALUES(6582, 'Pinheiral', 19);
INSERT INTO city(id,name,id_state) VALUES(6583, 'Pipeiras', 19);
INSERT INTO city(id,name,id_state) VALUES(6584, 'Pirai', 19);
INSERT INTO city(id,name,id_state) VALUES(6585, 'Pirangai', 19);
INSERT INTO city(id,name,id_state) VALUES(6586, 'Pirapetinga de Bom Jesus', 19);
INSERT INTO city(id,name,id_state) VALUES(6587, 'Porciuncula', 19);
INSERT INTO city(id,name,id_state) VALUES(6588, 'Portela', 19);
INSERT INTO city(id,name,id_state) VALUES(6589, 'Porto das Caixas', 19);
INSERT INTO city(id,name,id_state) VALUES(6590, 'Porto Real', 19);
INSERT INTO city(id,name,id_state) VALUES(6591, 'Porto Velho do Cunha', 19);
INSERT INTO city(id,name,id_state) VALUES(6592, 'Posse', 19);
INSERT INTO city(id,name,id_state) VALUES(6593, 'Praia de Aracatiba', 19);
INSERT INTO city(id,name,id_state) VALUES(6594, 'Pureza', 19);
INSERT INTO city(id,name,id_state) VALUES(6595, 'Purilandia', 19);
INSERT INTO city(id,name,id_state) VALUES(6596, 'Quarteis', 19);
INSERT INTO city(id,name,id_state) VALUES(6597, 'Quatis', 19);
INSERT INTO city(id,name,id_state) VALUES(6598, 'Queimados', 19);
INSERT INTO city(id,name,id_state) VALUES(6599, 'Quissama', 19);
INSERT INTO city(id,name,id_state) VALUES(6600, 'Renascenca', 19);
INSERT INTO city(id,name,id_state) VALUES(6601, 'Resende', 19);
INSERT INTO city(id,name,id_state) VALUES(6602, 'Retiro do Muriae', 19);
INSERT INTO city(id,name,id_state) VALUES(6603, 'Rialto', 19);
INSERT INTO city(id,name,id_state) VALUES(6604, 'Ribeirao de Sao Joaquim', 19);
INSERT INTO city(id,name,id_state) VALUES(6605, 'Rio Bonito', 19);
INSERT INTO city(id,name,id_state) VALUES(6606, 'Rio Claro', 19);
INSERT INTO city(id,name,id_state) VALUES(6607, 'Rio das Flores', 19);
INSERT INTO city(id,name,id_state) VALUES(6608, 'Rio das Ostras', 19);
INSERT INTO city(id,name,id_state) VALUES(6609, 'Rio de Janeiro', 19);
INSERT INTO city(id,name,id_state) VALUES(6610, 'Riograndina', 19);
INSERT INTO city(id,name,id_state) VALUES(6611, 'Rosal', 19);
INSERT INTO city(id,name,id_state) VALUES(6612, 'Sacra Familia do Tingua', 19);
INSERT INTO city(id,name,id_state) VALUES(6613, 'Salutaris', 19);
INSERT INTO city(id,name,id_state) VALUES(6614, 'Sambaetiba', 19);
INSERT INTO city(id,name,id_state) VALUES(6615, 'Sampaio Correia', 19);
INSERT INTO city(id,name,id_state) VALUES(6616, 'Sana', 19);
INSERT INTO city(id,name,id_state) VALUES(6617, 'Santa Clara', 19);
INSERT INTO city(id,name,id_state) VALUES(6618, 'Santa Cruz', 19);
INSERT INTO city(id,name,id_state) VALUES(6619, 'Santa Cruz da Serra', 19);
INSERT INTO city(id,name,id_state) VALUES(6620, 'Santa Isabel', 19);
INSERT INTO city(id,name,id_state) VALUES(6621, 'Santa Isabel do Rio Preto', 19);
INSERT INTO city(id,name,id_state) VALUES(6622, 'Santa Maria', 19);
INSERT INTO city(id,name,id_state) VALUES(6623, 'Santa Maria Madalena', 19);
INSERT INTO city(id,name,id_state) VALUES(6624, 'Santa Rita da Floresta', 19);
INSERT INTO city(id,name,id_state) VALUES(6625, 'Santanesia', 19);
INSERT INTO city(id,name,id_state) VALUES(6626, 'Santo Aleixo', 19);
INSERT INTO city(id,name,id_state) VALUES(6627, 'Santo Amaro de Campos', 19);
INSERT INTO city(id,name,id_state) VALUES(6628, 'Santo Antonio de Padua', 19);
INSERT INTO city(id,name,id_state) VALUES(6629, 'Santo Antonio do Imbe', 19);
INSERT INTO city(id,name,id_state) VALUES(6630, 'Santo Eduardo', 19);
INSERT INTO city(id,name,id_state) VALUES(6631, 'Sao Fidelis', 19);
INSERT INTO city(id,name,id_state) VALUES(6632, 'Sao Francisco de Paula', 19);
INSERT INTO city(id,name,id_state) VALUES(6633, 'Sao Goncalo', 19);
INSERT INTO city(id,name,id_state) VALUES(6634, 'Sao Joao da Barra', 19);
INSERT INTO city(id,name,id_state) VALUES(6635, 'Sao Joao de Meriti', 19);
INSERT INTO city(id,name,id_state) VALUES(6636, 'Sao Joao do Paraiso', 19);
INSERT INTO city(id,name,id_state) VALUES(6637, 'Sao Joao Marcos', 19);
INSERT INTO city(id,name,id_state) VALUES(6638, 'Sao Joaquim', 19);
INSERT INTO city(id,name,id_state) VALUES(6639, 'Sao Jose de Uba', 19);
INSERT INTO city(id,name,id_state) VALUES(6640, 'Sao Jose do Ribeirao', 19);
INSERT INTO city(id,name,id_state) VALUES(6641, 'Sao Jose do Turvo', 19);
INSERT INTO city(id,name,id_state) VALUES(6642, 'Sao Jose do Vale do Rio Preto', 19);
INSERT INTO city(id,name,id_state) VALUES(6643, 'Sao Mateus', 19);
INSERT INTO city(id,name,id_state) VALUES(6644, 'Sao Pedro da Aldeia', 19);
INSERT INTO city(id,name,id_state) VALUES(6645, 'Sao Sebastiao de Campos', 19);
INSERT INTO city(id,name,id_state) VALUES(6646, 'Sao Sebastiao do Alto', 19);
INSERT INTO city(id,name,id_state) VALUES(6647, 'Sao Sebastiao do Paraiba', 19);
INSERT INTO city(id,name,id_state) VALUES(6648, 'Sao Sebastiao dos Ferreiros', 19);
INSERT INTO city(id,name,id_state) VALUES(6649, 'Sao Vicente de Paula', 19);
INSERT INTO city(id,name,id_state) VALUES(6650, 'Sapucaia', 19);
INSERT INTO city(id,name,id_state) VALUES(6651, 'Saquarema', 19);
INSERT INTO city(id,name,id_state) VALUES(6652, 'Saracuruna', 19);
INSERT INTO city(id,name,id_state) VALUES(6653, 'Sebastiao de Lacerda', 19);
INSERT INTO city(id,name,id_state) VALUES(6654, 'Seropedica', 19);
INSERT INTO city(id,name,id_state) VALUES(6655, 'Serrinha', 19);
INSERT INTO city(id,name,id_state) VALUES(6656, 'Sete Pontes', 19);
INSERT INTO city(id,name,id_state) VALUES(6657, 'Silva Jardim', 19);
INSERT INTO city(id,name,id_state) VALUES(6658, 'Sodrelandia', 19);
INSERT INTO city(id,name,id_state) VALUES(6659, 'Sossego', 19);
INSERT INTO city(id,name,id_state) VALUES(6660, 'Subaio', 19);
INSERT INTO city(id,name,id_state) VALUES(6661, 'Sumidouro', 19);
INSERT INTO city(id,name,id_state) VALUES(6662, 'Surui', 19);
INSERT INTO city(id,name,id_state) VALUES(6663, 'Taboas', 19);
INSERT INTO city(id,name,id_state) VALUES(6664, 'Tamoios', 19);
INSERT INTO city(id,name,id_state) VALUES(6665, 'Tangua', 19);
INSERT INTO city(id,name,id_state) VALUES(6666, 'Tapera', 19);
INSERT INTO city(id,name,id_state) VALUES(6667, 'Tarituba', 19);
INSERT INTO city(id,name,id_state) VALUES(6668, 'Teresopolis', 19);
INSERT INTO city(id,name,id_state) VALUES(6669, 'Tocos', 19);
INSERT INTO city(id,name,id_state) VALUES(6670, 'Trajano de Morais', 19);
INSERT INTO city(id,name,id_state) VALUES(6671, 'Travessao', 19);
INSERT INTO city(id,name,id_state) VALUES(6672, 'Tres Irmaos', 19);
INSERT INTO city(id,name,id_state) VALUES(6673, 'Tres Rios', 19);
INSERT INTO city(id,name,id_state) VALUES(6674, 'Triunfo', 19);
INSERT INTO city(id,name,id_state) VALUES(6675, 'Valao do Barro', 19);
INSERT INTO city(id,name,id_state) VALUES(6676, 'Valenca', 19);
INSERT INTO city(id,name,id_state) VALUES(6677, 'Vargem Alegre', 19);
INSERT INTO city(id,name,id_state) VALUES(6678, 'Varre-Sai', 19);
INSERT INTO city(id,name,id_state) VALUES(6679, 'Vassouras', 19);
INSERT INTO city(id,name,id_state) VALUES(6680, 'Venda das Flores', 19);
INSERT INTO city(id,name,id_state) VALUES(6681, 'Venda das Pedras', 19);
INSERT INTO city(id,name,id_state) VALUES(6682, 'Vila da Grama', 19);
INSERT INTO city(id,name,id_state) VALUES(6683, 'Vila do Frade', 19);
INSERT INTO city(id,name,id_state) VALUES(6684, 'Vila Muriqui', 19);
INSERT INTO city(id,name,id_state) VALUES(6685, 'Vila Nova de Campos', 19);
INSERT INTO city(id,name,id_state) VALUES(6686, 'Visconde de Imbe', 19);
INSERT INTO city(id,name,id_state) VALUES(6687, 'Volta Redonda', 19);
INSERT INTO city(id,name,id_state) VALUES(6688, 'Werneck', 19);
INSERT INTO city(id,name,id_state) VALUES(6689, 'Xerem', 19);
